import { 
  Animal, 
  Animal360, 
  EspecieAnimal,
  PedigreeNode, 
  CurvaLactanciaPoint, 
  ControlLecheroPesaje, 
  RegistroPesaje, 
  TrasladoEspacialItem, 
  TratamientoSanitarioItem, 
  VacunaPlanItem 
} from '../../types/animal';

export const BASE_ANIMALS: Animal[] = [
  // ==========================================
  // 1. BOVINOS (VACUNOS)
  // ==========================================
  { 
    practico: "0001", 
    unico: "VE-01-0001-92", 
    categoria: "Vaca", 
    especie: "Bovinos",
    subcategoria: "Vacas",
    estatus: "Activo", 
    fechaNacimiento: "15/04/2021", 
    edad: "5,4 Años", 
    lote: "Lote 01", 
    descripcion: "Lote 01 - Alta Producción", 
    composicion: "Carora 75% x Holstein 25%", 
    racial: "Carora/Holstein", 
    etiquetas: "Élite, Ordeño", 
    activos: "Chip RFID, Arete", 
    padre: "CAR-092", 
    madre: "0045", 
    rfid: "982.000123849102", 
    estatusReproductivo: "Preñada", 
    diasGestacion: 142, 
    estatusProductivo: "Ordeño", 
    pesoKg: 560, 
    alertaSanitaria: "Retiro Activo (Mastitis PD)" 
  },
  { 
    practico: "0002", 
    unico: "VE-01-0002-88", 
    categoria: "Vaca", 
    especie: "Bovinos",
    subcategoria: "Vacas",
    estatus: "Activo", 
    fechaNacimiento: "16/10/2020", 
    edad: "5,9 Años", 
    lote: "Lote 01", 
    descripcion: "Lote 01 - Alta Producción", 
    composicion: "Pardo Suizo 50% x Brahman 50%", 
    racial: "F1 Doble Propósito", 
    etiquetas: "Ordeño", 
    activos: "Chip RFID, Arete", 
    padre: "PS-104", 
    madre: "BR-032", 
    rfid: "982.000123849103", 
    estatusReproductivo: "Vacía", 
    estatusProductivo: "Ordeño", 
    pesoKg: 520 
  },
  { 
    practico: "BCA05", 
    unico: "VE-01-BCA05-23", 
    categoria: "Vaca", 
    especie: "Bovinos",
    subcategoria: "Vacas",
    estatus: "Activo", 
    fechaNacimiento: "13/02/2022", 
    edad: "4,5 Años", 
    lote: "Lote 01", 
    descripcion: "Lote 01 - Alta Producción", 
    composicion: "Carora 100%", 
    racial: "Carora Puro", 
    etiquetas: "Seca", 
    activos: "Arete Visual, RFID", 
    padre: "CAR-014", 
    madre: "CAR-019", 
    rfid: "982.000123849109", 
    pesoKg: 510, 
    estatusReproductivo: "Preñada", 
    diasGestacion: 210, 
    estatusProductivo: "Seca" 
  },
  { 
    practico: "BCA03", 
    unico: "VE-01-BCA03-25", 
    categoria: "Novilla", 
    especie: "Bovinos",
    subcategoria: "Novillas",
    estatus: "Activo", 
    fechaNacimiento: "15/09/2024", 
    edad: "24,0 Meses", 
    lote: "POT2", 
    descripcion: "Potrero 2 - Novillas de Reemplazo", 
    composicion: "Carora x Brahman", 
    racial: "Mestizo", 
    etiquetas: "Servida", 
    activos: "Arete Visual, RFID", 
    padre: "CAR-092", 
    madre: "BR-032", 
    rfid: "982.000123849107", 
    pesoKg: 385, 
    estatusReproductivo: "En espera" 
  },
  { 
    practico: "BCA04", 
    unico: "VE-01-BCA04-25", 
    categoria: "Novilla", 
    especie: "Bovinos",
    subcategoria: "Novillas",
    estatus: "Activo", 
    fechaNacimiento: "15/09/2024", 
    edad: "24,0 Meses", 
    lote: "POT2", 
    descripcion: "Potrero 2 - Novillas de Reemplazo", 
    composicion: "Pardo Suizo 75%", 
    racial: "Pardo Suizo", 
    etiquetas: "Vientre", 
    activos: "Arete Visual", 
    padre: "PS-104", 
    madre: "CW013", 
    rfid: "982.000123849108", 
    pesoKg: 395, 
    estatusReproductivo: "Vacía" 
  },
  { 
    practico: "MAU01", 
    unico: "VE-01-MAU01-25", 
    categoria: "Mautas / Mautes", 
    especie: "Bovinos",
    subcategoria: "Mautas / Mautes",
    estatus: "Activo", 
    fechaNacimiento: "10/05/2025", 
    edad: "16,0 Meses", 
    lote: "POT3", 
    descripcion: "Potrero 3 - Mautas de Levante", 
    composicion: "Carora 60% x Girolando 40%", 
    racial: "Carora Mestizo", 
    etiquetas: "Levante", 
    activos: "Arete Visual", 
    padre: "CAR-092", 
    madre: "0002", 
    pesoKg: 285 
  },
  { 
    practico: "MAU02", 
    unico: "VE-01-MAU02-25", 
    categoria: "Mautas / Mautes", 
    especie: "Bovinos",
    subcategoria: "Mautas / Mautes",
    estatus: "Activo", 
    fechaNacimiento: "22/04/2025", 
    edad: "16,5 Meses", 
    lote: "POT3", 
    descripcion: "Potrero 3 - Mautes de Levante", 
    composicion: "Brahman Blanco x Pardo Suizo", 
    racial: "Mestizo Doble Propósito", 
    etiquetas: "Levante", 
    activos: "Arete Visual", 
    padre: "BR-101", 
    madre: "PS-04", 
    pesoKg: 310 
  },
  { 
    practico: "BCA01", 
    unico: "VE-01-BCA01-26", 
    categoria: "Becerros / Becerras", 
    especie: "Bovinos",
    subcategoria: "Becerros / Becerras",
    estatus: "Activo", 
    fechaNacimiento: "29/10/2025", 
    edad: "10,5 Meses", 
    lote: "POT1", 
    descripcion: "Potrero 1 - Terneraje", 
    composicion: "Carora 87.5% x Holstein 12.5%", 
    racial: "Carora", 
    etiquetas: "Cría 0001", 
    activos: "Arete Visual", 
    padre: "CAR-092", 
    madre: "0001", 
    rfid: "982.000123849105", 
    pesoKg: 198 
  },
  { 
    practico: "BCA02", 
    unico: "VE-01-BCA02-26", 
    categoria: "Becerros / Becerras", 
    especie: "Bovinos",
    subcategoria: "Becerros / Becerras",
    estatus: "Activo", 
    fechaNacimiento: "15/11/2025", 
    edad: "9,9 Meses", 
    lote: "POT1", 
    descripcion: "Potrero 1 - Terneraje", 
    composicion: "Girolando 5/8", 
    racial: "Girolando", 
    etiquetas: "Cría 0002", 
    activos: "Arete Visual", 
    padre: "GIR-04", 
    madre: "0002", 
    rfid: "982.000123849106", 
    pesoKg: 185 
  },
  { 
    practico: "TOR01", 
    unico: "VE-01-TOR01-19", 
    categoria: "Toros", 
    especie: "Bovinos",
    subcategoria: "Toros",
    estatus: "Activo", 
    fechaNacimiento: "04/01/2019", 
    edad: "7,5 Años", 
    lote: "POT-SEM", 
    descripcion: "Potrero Sementales Élite", 
    composicion: "Carora Puro Registrado", 
    racial: "Carora", 
    etiquetas: "Semental, Padrote", 
    activos: "Arete Visual, RFID, Tatuaje", 
    padre: "CAR-SUPREMO", 
    madre: "CAR-REINA", 
    pesoKg: 850 
  },
  { 
    practico: "TOR02", 
    unico: "VE-01-TOR02-20", 
    categoria: "Toros", 
    especie: "Bovinos",
    subcategoria: "Toros",
    estatus: "Activo", 
    fechaNacimiento: "14/03/2020", 
    edad: "6,4 Años", 
    lote: "POT-SEM", 
    descripcion: "Potrero Sementales Élite", 
    composicion: "Brahman Rojo Puro", 
    racial: "Brahman", 
    etiquetas: "Semental", 
    activos: "Arete Visual, RFID", 
    padre: "BR-ROJO-90", 
    madre: "BR-FLOR", 
    pesoKg: 890 
  },

  // ==========================================
  // 2. AVES DE CORRAL
  // ==========================================
  { 
    practico: "AVE-GP01", 
    unico: "AV-01-GP01-25", 
    categoria: "Gallinas Ponedoras", 
    especie: "Aves de corral",
    subcategoria: "Gallinas Ponedoras",
    estatus: "Activo", 
    fechaNacimiento: "10/01/2025", 
    edad: "1,6 Años", 
    lote: "GALP-01", 
    descripcion: "Galpón 01 - Postura Comercial", 
    composicion: "Lohmann Brown Clásica", 
    racial: "Lohmann Brown", 
    etiquetas: "Postura 94%, Huevos Marrones", 
    activos: "Anillo Pata ID", 
    padre: "LB-M90", 
    madre: "LB-F12", 
    pesoKg: 1.95, 
    estatusProductivo: "Postura Alta" 
  },
  { 
    practico: "AVE-GP02", 
    unico: "AV-01-GP02-25", 
    categoria: "Gallinas Ponedoras", 
    especie: "Aves de corral",
    subcategoria: "Gallinas Ponedoras",
    estatus: "Activo", 
    fechaNacimiento: "15/02/2025", 
    edad: "1,5 Años", 
    lote: "GALP-01", 
    descripcion: "Galpón 01 - Postura Comercial", 
    composicion: "Hy-Line Brown Línea Élite", 
    racial: "Hy-Line Brown", 
    etiquetas: "Postura 96%, Pico de Producción", 
    activos: "Anillo Pata ID", 
    padre: "HL-77", 
    madre: "HL-43", 
    pesoKg: 2.05, 
    estatusProductivo: "Postura Alta" 
  },
  { 
    practico: "AVE-PE01", 
    unico: "AV-01-PE01-26", 
    categoria: "Pollos de Engorde", 
    especie: "Aves de corral",
    subcategoria: "Pollos de Engorde",
    estatus: "Activo", 
    fechaNacimiento: "02/08/2026", 
    edad: "40 Días", 
    lote: "GALP-03", 
    descripcion: "Galpón 03 - Engorde Intensivo", 
    composicion: "Cobb 500 Pesado", 
    racial: "Cobb 500", 
    etiquetas: "Ceba Final, Alto Rendimiento Pechuga", 
    activos: "Control Lote Digital", 
    padre: "COBB-P", 
    madre: "COBB-M", 
    pesoKg: 2.55, 
    estatusProductivo: "Ceba" 
  },
  { 
    practico: "AVE-PE02", 
    unico: "AV-01-PE02-26", 
    categoria: "Pollos de Engorde", 
    especie: "Aves de corral",
    subcategoria: "Pollos de Engorde",
    estatus: "Activo", 
    fechaNacimiento: "06/08/2026", 
    edad: "36 Días", 
    lote: "GALP-03", 
    descripcion: "Galpón 03 - Engorde Intensivo", 
    composicion: "Ross 308 Plus", 
    racial: "Ross 308", 
    etiquetas: "Conversión Forrajera 1.62", 
    activos: "Control Lote Digital", 
    padre: "ROSS-P", 
    madre: "ROSS-M", 
    pesoKg: 2.35, 
    estatusProductivo: "Ceba" 
  },
  { 
    practico: "AVE-PO01", 
    unico: "AV-01-PO01-26", 
    categoria: "Pollonas / Pollitos", 
    especie: "Aves de corral",
    subcategoria: "Pollonas / Pollitos",
    estatus: "Activo", 
    fechaNacimiento: "01/06/2026", 
    edad: "14 Semanas", 
    lote: "GALP-LEV", 
    descripcion: "Galpón Levante A", 
    composicion: "Lohmann Brown Reemplazo", 
    racial: "Lohmann Brown", 
    etiquetas: "Levante, Vacunación Completa", 
    activos: "Micro-anillo", 
    padre: "LB-LEV", 
    madre: "LB-MAT", 
    pesoKg: 1.25, 
    estatusProductivo: "Levante" 
  },
  { 
    practico: "AVE-PO02", 
    unico: "AV-01-PO02-26", 
    categoria: "Pollonas / Pollitos", 
    especie: "Aves de corral",
    subcategoria: "Pollonas / Pollitos",
    estatus: "Activo", 
    fechaNacimiento: "05/09/2026", 
    edad: "7 Días", 
    lote: "CRIAD-01", 
    descripcion: "Criadora Térmica Central", 
    composicion: "Pollitos BB Línea Pesada", 
    racial: "Cobb 500", 
    etiquetas: "Iniciación, Calefacción 32°C", 
    activos: "Control Lote", 
    padre: "P-BB", 
    madre: "M-BB", 
    pesoKg: 0.16, 
    estatusProductivo: "Cría" 
  },
  { 
    practico: "AVE-GF01", 
    unico: "AV-01-GF01-24", 
    categoria: "Gallos Finos", 
    especie: "Aves de corral",
    subcategoria: "Gallos Finos",
    estatus: "Activo", 
    fechaNacimiento: "10/03/2024", 
    edad: "2,4 Años", 
    lote: "CAS-ELITE", 
    descripcion: "Casillero Élite 01", 
    composicion: "Marañón Español Puro", 
    racial: "Combatiente Español", 
    etiquetas: "Casta Élite, Púa Corta", 
    activos: "Tatuaje Ala, Anillo Acero", 
    padre: "MARAN-09", 
    madre: "FINA-01", 
    pesoKg: 3.25 
  },
  { 
    practico: "AVE-GF02", 
    unico: "AV-01-GF02-24", 
    categoria: "Gallos Finos", 
    especie: "Aves de corral",
    subcategoria: "Gallos Finos",
    estatus: "Activo", 
    fechaNacimiento: "20/07/2024", 
    edad: "2,1 Años", 
    lote: "CAS-ELITE", 
    descripcion: "Casillero Élite 02", 
    composicion: "Giro Dominicano x Marañón", 
    racial: "Giro de Casta", 
    etiquetas: "Plumaje Sedoso, Rapidez", 
    activos: "Anillo Acero", 
    padre: "GIRO-01", 
    madre: "MARAN-04", 
    pesoKg: 3.35 
  },
  { 
    practico: "AVE-GAF01", 
    unico: "AV-01-GAF01-24", 
    categoria: "Gallinas Finas", 
    especie: "Aves de corral",
    subcategoria: "Gallinas Finas",
    estatus: "Activo", 
    fechaNacimiento: "12/04/2024", 
    edad: "2,3 Años", 
    lote: "CRIA-FINA", 
    descripcion: "Criadero Matriz Casta 1", 
    composicion: "Gallina Ceniza de Casta", 
    racial: "Combatiente Pura", 
    etiquetas: "Matriz Probada, Excelente Madre", 
    activos: "Anillo Pata", 
    padre: "CEN-01", 
    madre: "FINA-08", 
    pesoKg: 2.45 
  },
  { 
    practico: "AVE-GAF02", 
    unico: "AV-01-GAF02-24", 
    categoria: "Gallinas Finas", 
    especie: "Aves de corral",
    subcategoria: "Gallinas Finas",
    estatus: "Activo", 
    fechaNacimiento: "18/08/2024", 
    edad: "2,0 Años", 
    lote: "CRIA-FINA", 
    descripcion: "Criadero Matriz Casta 2", 
    composicion: "Gallina Pinta Alirroja", 
    racial: "Combatiente Pura", 
    etiquetas: "Genética Seleccionada", 
    activos: "Anillo Pata", 
    padre: "ROJO-02", 
    madre: "PINTA-05", 
    pesoKg: 2.50 
  },
  { 
    practico: "AVE-PV01", 
    unico: "AV-01-PV01-25", 
    categoria: "Pavos / Pavas", 
    especie: "Aves de corral",
    subcategoria: "Pavos / Pavas",
    estatus: "Activo", 
    fechaNacimiento: "15/10/2025", 
    edad: "11,0 Meses", 
    lote: "GALP-PAVOS", 
    descripcion: "Galpón Pavos de Carne", 
    composicion: "Nicholas 700 Doble Pechuga", 
    racial: "Pavo Blanco Comercial", 
    etiquetas: "Peso Pesado, Excelente Conversión", 
    activos: "Marca Alar", 
    padre: "NICH-01", 
    madre: "NICH-09", 
    pesoKg: 14.8 
  },
  { 
    practico: "AVE-PV02", 
    unico: "AV-01-PV02-25", 
    categoria: "Pavos / Pavas", 
    especie: "Aves de corral",
    subcategoria: "Pavos / Pavas",
    estatus: "Activo", 
    fechaNacimiento: "20/09/2025", 
    edad: "11,8 Meses", 
    lote: "GALP-PAVOS", 
    descripcion: "Galpón Pavos de Carne", 
    composicion: "Pava Bronceada Americana", 
    racial: "Bronceada Gigante", 
    etiquetas: "Hembra Reproductora", 
    activos: "Marca Alar", 
    padre: "BRONC-03", 
    madre: "BRONC-12", 
    pesoKg: 9.9 
  },
  { 
    practico: "AVE-PT01", 
    unico: "AV-01-PT01-25", 
    categoria: "Patos / Patas", 
    especie: "Aves de corral",
    subcategoria: "Patos / Patas",
    estatus: "Activo", 
    fechaNacimiento: "14/11/2025", 
    edad: "9,8 Meses", 
    lote: "LAG-NORTE", 
    descripcion: "Laguna y Estanque Norte", 
    composicion: "Pato Pekín Americano", 
    racial: "Pekín Blanco", 
    etiquetas: "Macho Reproductor, Resistente", 
    activos: "Anillo Flotante", 
    padre: "PEK-01", 
    madre: "PEK-10", 
    pesoKg: 3.85 
  },
  { 
    practico: "AVE-PT02", 
    unico: "AV-01-PT02-25", 
    categoria: "Patos / Patas", 
    especie: "Aves de corral",
    subcategoria: "Patos / Patas",
    estatus: "Activo", 
    fechaNacimiento: "14/11/2025", 
    edad: "9,8 Meses", 
    lote: "LAG-NORTE", 
    descripcion: "Laguna y Estanque Norte", 
    composicion: "Pata Pekín Criadora", 
    racial: "Pekín Blanco", 
    etiquetas: "Hembra, Buena Postura", 
    activos: "Anillo Flotante", 
    padre: "PEK-01", 
    madre: "PEK-14", 
    pesoKg: 3.30 
  },
  { 
    practico: "AVE-PP01", 
    unico: "AV-01-PP01-26", 
    categoria: "Pavitos / Patitos", 
    especie: "Aves de corral",
    subcategoria: "Pavitos / Patitos",
    estatus: "Activo", 
    fechaNacimiento: "18/08/2026", 
    edad: "24 Días", 
    lote: "CRIAD-02", 
    descripcion: "Criadora Pavitos 02", 
    composicion: "Lote Pavitos Blanco Nicholas", 
    racial: "Pavitos Comercial", 
    etiquetas: "Iniciador con Coccidiostato", 
    activos: "Identificación de Corral", 
    padre: "NICH-01", 
    madre: "NICH-09", 
    pesoKg: 0.52 
  },
  { 
    practico: "AVE-PP02", 
    unico: "AV-01-PP02-26", 
    categoria: "Pavitos / Patitos", 
    especie: "Aves de corral",
    subcategoria: "Pavitos / Patitos",
    estatus: "Activo", 
    fechaNacimiento: "28/08/2026", 
    edad: "14 Días", 
    lote: "EST-REC", 
    descripcion: "Área Recría Patitos", 
    composicion: "Patitos Pekín de Granja", 
    racial: "Pekín", 
    etiquetas: "Patitos de Agua, Crecimiento Rápido", 
    activos: "Identificación de Corral", 
    padre: "PEK-01", 
    madre: "PEK-10", 
    pesoKg: 0.32 
  },

  // ==========================================
  // 3. PORCINOS
  // ==========================================
  { 
    practico: "POR-CR01", 
    unico: "PC-01-CR01-23", 
    categoria: "Cerdas Reproductoras", 
    especie: "Porcinos",
    subcategoria: "Cerdas Reproductoras",
    estatus: "Activo", 
    fechaNacimiento: "10/03/2023", 
    edad: "3,5 Años", 
    lote: "COCH-PAR", 
    descripcion: "Cochinera - Sala Maternidad 4", 
    composicion: "Landrace 50% x Large White 50%", 
    racial: "F1 Maternal", 
    etiquetas: "14 Nacidos Vivos, Habilidad Materna", 
    activos: "Arete Electrónico Porcino", 
    padre: "LAND-10", 
    madre: "LW-22", 
    pesoKg: 235, 
    estatusReproductivo: "Lactando", 
    partos: 4 
  },
  { 
    practico: "POR-CR02", 
    unico: "PC-01-CR02-23", 
    categoria: "Cerdas Reproductoras", 
    especie: "Porcinos",
    subcategoria: "Cerdas Reproductoras",
    estatus: "Activo", 
    fechaNacimiento: "15/05/2023", 
    edad: "3,3 Años", 
    lote: "COCH-GEST", 
    descripcion: "Cochinera - Gestación Confirmada", 
    composicion: "Duroc x Landrace", 
    racial: "Maternal F1", 
    etiquetas: "Preñada (85d), Ecografía Positiva", 
    activos: "Arete Visual", 
    padre: "DUR-01", 
    madre: "LAND-08", 
    pesoKg: 248, 
    estatusReproductivo: "Preñada", 
    diasGestacion: 85, 
    partos: 3 
  },
  { 
    practico: "POR-VR01", 
    unico: "PC-01-VR01-23", 
    categoria: "Verracos", 
    especie: "Porcinos",
    subcategoria: "Verracos",
    estatus: "Activo", 
    fechaNacimiento: "02/02/2023", 
    edad: "3,6 Años", 
    lote: "CORR-VERR", 
    descripcion: "Corral Verracos Terminadores", 
    composicion: "Pietrain Alemán Puro", 
    racial: "Pietrain", 
    etiquetas: "Semental Terminal, Libre Halotano", 
    activos: "Tatuaje Oreja, Arete", 
    padre: "PIET-TITAN", 
    madre: "PIET-04", 
    pesoKg: 285 
  },
  { 
    practico: "POR-VR02", 
    unico: "PC-01-VR02-24", 
    categoria: "Verracos", 
    especie: "Porcinos",
    subcategoria: "Verracos",
    estatus: "Activo", 
    fechaNacimiento: "18/01/2024", 
    edad: "2,6 Años", 
    lote: "CORR-VERR", 
    descripcion: "Corral Verracos Terminadores", 
    composicion: "Duroc Jersey Línea Carne", 
    racial: "Duroc", 
    etiquetas: "Vigor Híbrido, Alta Libido", 
    activos: "Arete Visual", 
    padre: "DUR-RED", 
    madre: "DUR-MA", 
    pesoKg: 310 
  },
  { 
    practico: "POR-LC01", 
    unico: "PC-01-LC01-26", 
    categoria: "Lechones", 
    especie: "Porcinos",
    subcategoria: "Lechones",
    estatus: "Activo", 
    fechaNacimiento: "15/08/2026", 
    edad: "28 Días", 
    lote: "COCH-PAR", 
    descripcion: "Sala Maternidad - Camada 104", 
    composicion: "Pietrain x (Landrace x Large White)", 
    racial: "Tres Vías Comercial", 
    etiquetas: "Pre-destete, Calostro Adecuado", 
    activos: "Muesca Auricular", 
    padre: "POR-VR01", 
    madre: "POR-CR01", 
    pesoKg: 7.8 
  },
  { 
    practico: "POR-LC02", 
    unico: "PC-01-LC02-26", 
    categoria: "Lechones", 
    especie: "Porcinos",
    subcategoria: "Lechones",
    estatus: "Activo", 
    fechaNacimiento: "28/07/2026", 
    edad: "46 Días", 
    lote: "COCH-TRANS", 
    descripcion: "Batería Transición 1", 
    composicion: "Duroc x Maternal", 
    racial: "Comercial Cárnico", 
    etiquetas: "Destetado, Consumo Balanceado", 
    activos: "Arete Mini", 
    padre: "POR-VR02", 
    madre: "POR-CR02", 
    pesoKg: 15.2 
  },
  { 
    practico: "POR-CB01", 
    unico: "PC-01-CB01-26", 
    categoria: "Cerdos de Ceba", 
    especie: "Porcinos",
    subcategoria: "Cerdos de Ceba",
    estatus: "Activo", 
    fechaNacimiento: "10/04/2026", 
    edad: "5,0 Meses", 
    lote: "GALP-ENG1", 
    descripcion: "Galpón Engorde Porcino 1", 
    composicion: "Pietrain x Landrace", 
    racial: "Terminal", 
    etiquetas: "Ceba Fase 2, GDP 850g/d", 
    activos: "Arete Visual", 
    padre: "POR-VR01", 
    madre: "POR-CR01", 
    pesoKg: 86.5 
  },
  { 
    practico: "POR-CB02", 
    unico: "PC-01-CB02-26", 
    categoria: "Cerdos de Ceba", 
    especie: "Porcinos",
    subcategoria: "Cerdos de Ceba",
    estatus: "Activo", 
    fechaNacimiento: "15/03/2026", 
    edad: "5,8 Meses", 
    lote: "GALP-ENG2", 
    descripcion: "Galpón Engorde Porcino 2", 
    composicion: "Duroc x F1 Maternal", 
    racial: "Terminal Cárnico", 
    etiquetas: "Listo para Matadero, Espesor Grasa Dorsal Óptimo", 
    activos: "Arete Visual", 
    padre: "POR-VR02", 
    madre: "POR-CR02", 
    pesoKg: 108.0 
  },
  { 
    practico: "POR-RP01", 
    unico: "PC-01-RP01-26", 
    categoria: "Cerdas de Reemplazo", 
    especie: "Porcinos",
    subcategoria: "Cerdas de Reemplazo",
    estatus: "Activo", 
    fechaNacimiento: "12/02/2026", 
    edad: "7,0 Meses", 
    lote: "COCH-REEMP", 
    descripcion: "Lote Cerdas de Reemplazo", 
    composicion: "Topigs 20 Camborough", 
    racial: "Línea Maternal", 
    etiquetas: "Futura Matriz, 14 pezones funcionales", 
    activos: "Arete RFID", 
    padre: "TOP-01", 
    madre: "TOP-99", 
    pesoKg: 115.0 
  },
  { 
    practico: "POR-RP02", 
    unico: "PC-01-RP02-26", 
    categoria: "Cerdas de Reemplazo", 
    especie: "Porcinos",
    subcategoria: "Cerdas de Reemplazo",
    estatus: "Activo", 
    fechaNacimiento: "01/03/2026", 
    edad: "6,4 Meses", 
    lote: "COCH-REEMP", 
    descripcion: "Lote Cerdas de Reemplazo", 
    composicion: "Large White Puro", 
    racial: "Large White", 
    etiquetas: "Reemplazo Seleccionado", 
    activos: "Arete RFID", 
    padre: "LW-CAN", 
    madre: "LW-08", 
    pesoKg: 104.0 
  },

  // ==========================================
  // 4. BÚFALOS
  // ==========================================
  { 
    practico: "BUF-01", 
    unico: "BF-01-BUF01-20", 
    categoria: "Búfalas", 
    especie: "Búfalos",
    subcategoria: "Búfalas",
    estatus: "Activo", 
    fechaNacimiento: "18/06/2020", 
    edad: "6,2 Años", 
    lote: "SAB-BAJA", 
    descripcion: "Lote Sabana Baja y Bajíos", 
    composicion: "Murrah Pura", 
    racial: "Murrah", 
    etiquetas: "Ordeño Búfala, 8.5 L/d, Grasa 7.8%", 
    activos: "Chip RFID, Arete Metálico", 
    padre: "MUR-RAJA", 
    madre: "MUR-LUNA", 
    rfid: "982.000450000001", 
    estatusReproductivo: "Preñada", 
    diasGestacion: 180, 
    estatusProductivo: "Ordeño", 
    pesoKg: 620 
  },
  { 
    practico: "BUF-02", 
    unico: "BF-01-BUF02-21", 
    categoria: "Búfalas", 
    especie: "Búfalos",
    subcategoria: "Búfalas",
    estatus: "Activo", 
    fechaNacimiento: "12/09/2021", 
    edad: "5,0 Años", 
    lote: "SAB-BAJA", 
    descripcion: "Lote Sabana Baja y Bajíos", 
    composicion: "Mediterránea Italiana 100%", 
    racial: "Mediterráneo", 
    etiquetas: "Ordeño Búfala, Mozzarella Alta Grasa", 
    activos: "Arete Visual, RFID", 
    padre: "MED-ROMA", 
    madre: "MED-BELLA", 
    rfid: "982.000450000002", 
    estatusReproductivo: "Vacía", 
    estatusProductivo: "Ordeño", 
    pesoKg: 590 
  },
  { 
    practico: "BUF-BU01", 
    unico: "BF-01-BU01-24", 
    categoria: "Bubillas", 
    especie: "Búfalos",
    subcategoria: "Bubillas",
    estatus: "Activo", 
    fechaNacimiento: "15/10/2024", 
    edad: "23,0 Meses", 
    lote: "POT-BUF-REC", 
    descripcion: "Potrero Bubillas de Reemplazo", 
    composicion: "Murrah 87.5% x Mediterráneo 12.5%", 
    racial: "Murrah", 
    etiquetas: "Vientre Futuro, Crecimiento Rápido", 
    activos: "Arete Visual", 
    padre: "MUR-RAJA", 
    madre: "BUF-02", 
    pesoKg: 385 
  },
  { 
    practico: "BUF-BU02", 
    unico: "BF-01-BU02-24", 
    categoria: "Bubillas", 
    especie: "Búfalos",
    subcategoria: "Bubillas",
    estatus: "Activo", 
    fechaNacimiento: "05/12/2024", 
    edad: "21,2 Meses", 
    lote: "POT-BUF-REC", 
    descripcion: "Potrero Bubillas de Reemplazo", 
    composicion: "Jafarabadi x Murrah", 
    racial: "Mestizo Bufalino", 
    etiquetas: "Levante Rústico", 
    activos: "Arete Visual", 
    padre: "JAF-02", 
    madre: "BUF-01", 
    pesoKg: 370 
  },
  { 
    practico: "BUF-BC01", 
    unico: "BF-01-BC01-26", 
    categoria: "Bucerros / Bucerras", 
    especie: "Búfalos",
    subcategoria: "Bucerros / Bucerras",
    estatus: "Activo", 
    fechaNacimiento: "10/05/2026", 
    edad: "4,0 Meses", 
    lote: "MAT-BUF", 
    descripcion: "Maternidad Bufalina", 
    composicion: "Murrah Pura", 
    racial: "Murrah", 
    etiquetas: "Bucerra Lactante, Cría de Morena", 
    activos: "Arete Visual", 
    padre: "BUF-PD01", 
    madre: "BUF-01", 
    pesoKg: 120 
  },
  { 
    practico: "BUF-BC02", 
    unico: "BF-01-BC02-26", 
    categoria: "Bucerros / Bucerras", 
    especie: "Búfalos",
    subcategoria: "Bucerros / Bucerras",
    estatus: "Activo", 
    fechaNacimiento: "22/03/2026", 
    edad: "5,6 Meses", 
    lote: "MAT-BUF", 
    descripcion: "Maternidad Bufalina", 
    composicion: "Mediterráneo Puro", 
    racial: "Mediterráneo", 
    etiquetas: "Bucerro Macho, Gran Desarrollo", 
    activos: "Arete Visual", 
    padre: "MED-ROMA", 
    madre: "BUF-02", 
    pesoKg: 148 
  },
  { 
    practico: "BUF-PD01", 
    unico: "BF-01-PD01-18", 
    categoria: "Padrotes / Búfalos de Ceba", 
    especie: "Búfalos",
    subcategoria: "Padrotes / Búfalos de Ceba",
    estatus: "Activo", 
    fechaNacimiento: "10/08/2018", 
    edad: "8,1 Años", 
    lote: "POT-PAD-BUF", 
    descripcion: "Potrero Padrotes Búfalo", 
    composicion: "Murrah Indio Élite 'El Sultán'", 
    racial: "Murrah Puro", 
    etiquetas: "Padrote Principal, Mansedumbre", 
    activos: "Arete Visual, RFID", 
    padre: "MUR-SULTAN-SR", 
    madre: "MUR-MADRE", 
    pesoKg: 890 
  },
  { 
    practico: "BUF-CB01", 
    unico: "BF-01-CB01-23", 
    categoria: "Padrotes / Búfalos de Ceba", 
    especie: "Búfalos",
    subcategoria: "Padrotes / Búfalos de Ceba",
    estatus: "Activo", 
    fechaNacimiento: "14/09/2023", 
    edad: "3,0 Años", 
    lote: "CEBA-BUF", 
    descripcion: "Lote Ceba Bufalina", 
    composicion: "Mestizo Bufalino Sabana", 
    racial: "Búfalo de Agua", 
    etiquetas: "Ceba Intensiva en Pasto Húmedo", 
    activos: "Arete Visual", 
    padre: "BUF-PD01", 
    madre: "BUF-02", 
    pesoKg: 525 
  },

  // ==========================================
  // 5. CAPRINOS
  // ==========================================
  { 
    practico: "CAP-CL01", 
    unico: "CP-01-CL01-23", 
    categoria: "Cabras Lecheras", 
    especie: "Caprinos",
    subcategoria: "Cabras Lecheras",
    estatus: "Activo", 
    fechaNacimiento: "14/02/2023", 
    edad: "3,5 Años", 
    lote: "APR-ORD", 
    descripcion: "Aprisco Central - Ordeño", 
    composicion: "Alpina Francesa 100%", 
    racial: "Alpina", 
    etiquetas: "Ordeño 3.8 L/d, Ubre Espaciosa", 
    activos: "Arete Microchip Caprino", 
    padre: "ALP-PARIS", 
    madre: "ALP-BLANCA", 
    pesoKg: 58, 
    estatusProductivo: "Ordeño", 
    estatusReproductivo: "Preñada", 
    diasGestacion: 72 
  },
  { 
    practico: "CAP-CL02", 
    unico: "CP-01-CL02-23", 
    categoria: "Cabras Lecheras", 
    especie: "Caprinos",
    subcategoria: "Cabras Lecheras",
    estatus: "Activo", 
    fechaNacimiento: "20/04/2023", 
    edad: "3,4 Años", 
    lote: "APR-ORD", 
    descripcion: "Aprisco Central - Ordeño", 
    composicion: "Saanen Suiza Lechera", 
    racial: "Saanen", 
    etiquetas: "Ordeño 4.2 L/d, Alta Persistencia", 
    activos: "Arete Microchip", 
    padre: "SAAN-SUIZA", 
    madre: "SAAN-ALPES", 
    pesoKg: 62, 
    estatusProductivo: "Ordeño", 
    estatusReproductivo: "Vacía" 
  },
  { 
    practico: "CAP-CB01", 
    unico: "CP-01-CB01-25", 
    categoria: "Cabritonas / Cabritos", 
    especie: "Caprinos",
    subcategoria: "Cabritonas / Cabritos",
    estatus: "Activo", 
    fechaNacimiento: "10/11/2025", 
    edad: "10,0 Meses", 
    lote: "APR-LEV", 
    descripcion: "Aprisco Levante Caprino", 
    composicion: "Saanen x Alpina", 
    racial: "Mestizo Lechero", 
    etiquetas: "Cabritona de Reemplazo", 
    activos: "Arete Plástico", 
    padre: "SAAN-SUIZA", 
    madre: "CAP-CL01", 
    pesoKg: 29 
  },
  { 
    practico: "CAP-CB02", 
    unico: "CP-01-CB02-26", 
    categoria: "Cabritonas / Cabritos", 
    especie: "Caprinos",
    subcategoria: "Cabritonas / Cabritos",
    estatus: "Activo", 
    fechaNacimiento: "15/02/2026", 
    edad: "6,9 Meses", 
    lote: "APR-LEV", 
    descripcion: "Aprisco Levante Caprino", 
    composicion: "Anglo Nubian Puro", 
    racial: "Anglo Nubian", 
    etiquetas: "Cabrito Macho, Orejas Caídas", 
    activos: "Arete Plástico", 
    padre: "NUB-LORD", 
    madre: "NUB-LADY", 
    pesoKg: 25 
  },
  { 
    practico: "CAP-CH01", 
    unico: "CP-01-CH01-22", 
    categoria: "Chivos Reproductores", 
    especie: "Caprinos",
    subcategoria: "Chivos Reproductores",
    estatus: "Activo", 
    fechaNacimiento: "08/08/2022", 
    edad: "4,1 Años", 
    lote: "PIQ-CHIVOS", 
    descripcion: "Piquete Reproductores Caprinos", 
    composicion: "Boer Sudafricano Puro", 
    racial: "Boer", 
    etiquetas: "Padrote Cárnico, Cabeza Roja 98 kg", 
    activos: "Arete Tatuaje", 
    padre: "BOER-CHAMPION", 
    madre: "BOER-ROSA", 
    pesoKg: 98 
  },
  { 
    practico: "CAP-CH02", 
    unico: "CP-01-CH02-23", 
    categoria: "Chivos Reproductores", 
    especie: "Caprinos",
    subcategoria: "Chivos Reproductores",
    estatus: "Activo", 
    fechaNacimiento: "03/03/2023", 
    edad: "3,5 Años", 
    lote: "PIQ-CHIVOS", 
    descripcion: "Piquete Reproductores Caprinos", 
    composicion: "Alpino Francés Lechero", 
    racial: "Alpina", 
    etiquetas: "Transmisor Leche y Ubres", 
    activos: "Arete Tatuaje", 
    padre: "ALP-FRANCE", 
    madre: "ALP-VAL", 
    pesoKg: 85 
  },
  { 
    practico: "CAP-CE01", 
    unico: "CP-01-CE01-25", 
    categoria: "Caprinos de Ceba", 
    especie: "Caprinos",
    subcategoria: "Caprinos de Ceba",
    estatus: "Activo", 
    fechaNacimiento: "05/10/2025", 
    edad: "11,2 Meses", 
    lote: "APR-CEBA", 
    descripcion: "Aprisco Ceba y Engorde", 
    composicion: "Boer 50% x Criollo 50%", 
    racial: "Boer Mestizo", 
    etiquetas: "Ceba Semi-estabulada", 
    activos: "Arete Visual", 
    padre: "CAP-CH01", 
    madre: "CAP-CRIOLLA", 
    pesoKg: 38 
  },
  { 
    practico: "CAP-CE02", 
    unico: "CP-01-CE02-25", 
    categoria: "Caprinos de Ceba", 
    especie: "Caprinos",
    subcategoria: "Caprinos de Ceba",
    estatus: "Activo", 
    fechaNacimiento: "20/09/2025", 
    edad: "11,7 Meses", 
    lote: "APR-CEBA", 
    descripcion: "Aprisco Ceba y Engorde", 
    composicion: "Boer 75% x Anglo Nubian 25%", 
    racial: "F1 Carne", 
    etiquetas: "Terminación Cárnica", 
    activos: "Arete Visual", 
    padre: "CAP-CH01", 
    madre: "NUB-LADY", 
    pesoKg: 43 
  },

  // ==========================================
  // 6. EQUINOS
  // ==========================================
  { 
    practico: "EQU-YG01", 
    unico: "EQ-01-YG01-20", 
    categoria: "Yeguas", 
    especie: "Equinos",
    subcategoria: "Yeguas",
    estatus: "Activo", 
    fechaNacimiento: "12/05/2020", 
    edad: "6,3 Años", 
    lote: "POT-CABALL", 
    descripcion: "Potrero Caballerizas", 
    composicion: "Cuarto de Milla de Trabajo", 
    racial: "Quarter Horse", 
    etiquetas: "Yegua Matriz, Registro AQHA", 
    activos: "Hierro Caliente, Chip Nuca", 
    padre: "QM-DOC-BAR", 
    madre: "QM-BELLA", 
    pesoKg: 495, 
    estatusReproductivo: "Preñada", 
    diasGestacion: 210 
  },
  { 
    practico: "EQU-YG02", 
    unico: "EQ-01-YG02-19", 
    categoria: "Yeguas", 
    especie: "Equinos",
    subcategoria: "Yeguas",
    estatus: "Activo", 
    fechaNacimiento: "04/04/2019", 
    edad: "7,4 Años", 
    lote: "POT-CABALL", 
    descripcion: "Potrero Caballerizas", 
    composicion: "Criolla Llanera Autóctona", 
    racial: "Criollo", 
    etiquetas: "Faena Llanera, Gran Resistencia", 
    activos: "Hierro Caliente", 
    padre: "LLAN-01", 
    madre: "LLAN-09", 
    pesoKg: 440, 
    estatusReproductivo: "Vacía" 
  },
  { 
    practico: "EQU-PT01", 
    unico: "EQ-01-PT01-25", 
    categoria: "Potros / Potrancas", 
    especie: "Equinos",
    subcategoria: "Potros / Potrancas",
    estatus: "Activo", 
    fechaNacimiento: "15/03/2025", 
    edad: "17,9 Meses", 
    lote: "PICADERO", 
    descripcion: "Picadero y Entrenamiento", 
    composicion: "Paso Fino Colombiano", 
    racial: "Paso Fino", 
    etiquetas: "Potranca de Brío, Inicio de Cuerda", 
    activos: "Microchip Nuca", 
    padre: "PF-TORMENTO", 
    madre: "PF-DINASTIA", 
    pesoKg: 320 
  },
  { 
    practico: "EQU-PT02", 
    unico: "EQ-01-PT02-24", 
    categoria: "Potros / Potrancas", 
    especie: "Equinos",
    subcategoria: "Potros / Potrancas",
    estatus: "Activo", 
    fechaNacimiento: "10/11/2024", 
    edad: "22,0 Meses", 
    lote: "PICADERO", 
    descripcion: "Picadero y Amansamiento", 
    composicion: "Cuarto de Milla Línea Rienda", 
    racial: "Quarter Horse", 
    etiquetas: "Potro Alazán, Mansedumbre", 
    activos: "Microchip Nuca", 
    padre: "EQU-PD01", 
    madre: "EQU-YG01", 
    pesoKg: 365 
  },
  { 
    practico: "EQU-CB01", 
    unico: "EQ-01-CB01-18", 
    categoria: "Caballos", 
    especie: "Equinos",
    subcategoria: "Caballos",
    estatus: "Activo", 
    fechaNacimiento: "10/02/2018", 
    edad: "8,6 Años", 
    lote: "CABALLERIZA-02", 
    descripcion: "Caballeriza de Vaquería", 
    composicion: "Mestizo Cuarto de Milla x Criollo", 
    racial: "Mestizo de Trabajo", 
    etiquetas: "Caballo Vaquero Experto, 'El Alazán'", 
    activos: "Hierro en Paleta", 
    padre: "QM-CORONEL", 
    madre: "CRI-VIEJA", 
    pesoKg: 475 
  },
  { 
    practico: "EQU-CB02", 
    unico: "EQ-01-CB02-20", 
    categoria: "Caballos", 
    especie: "Equinos",
    subcategoria: "Caballos",
    estatus: "Activo", 
    fechaNacimiento: "24/08/2020", 
    edad: "6,0 Años", 
    lote: "CABALLERIZA-01", 
    descripcion: "Caballeriza Principal", 
    composicion: "Palomino Cuarto de Milla", 
    racial: "Palomino", 
    etiquetas: "Caballo de Paseo y Ronda", 
    activos: "Microchip", 
    padre: "PAL-GOLD", 
    madre: "EQU-YG02", 
    pesoKg: 480 
  },
  { 
    practico: "EQU-PD01", 
    unico: "EQ-01-PD01-17", 
    categoria: "Padrillos / Sementales", 
    especie: "Equinos",
    subcategoria: "Padrillos / Sementales",
    estatus: "Activo", 
    fechaNacimiento: "12/04/2017", 
    edad: "9,4 Años", 
    lote: "PESEB-SEM", 
    descripcion: "Pesebrera Semental 'Rey Llanero'", 
    composicion: "Cuarto de Milla Puro Línea Shining Spark", 
    racial: "Quarter Horse", 
    etiquetas: "Padrillo de Registro, Gran Campeón", 
    activos: "Tatuaje Labio, Microchip", 
    padre: "SHINING-CHAMP", 
    madre: "SPARK-LADY", 
    pesoKg: 535 
  },
  { 
    practico: "EQU-PD02", 
    unico: "EQ-01-PD02-18", 
    categoria: "Padrillos / Sementales", 
    especie: "Equinos",
    subcategoria: "Padrillos / Sementales",
    estatus: "Activo", 
    fechaNacimiento: "15/07/2018", 
    edad: "8,1 Años", 
    lote: "PESEB-SEM", 
    descripcion: "Pesebrera Semental Árabe", 
    composicion: "Árabe Puro de Conformación", 
    racial: "Pura Sangre Árabe", 
    etiquetas: "Semental Nobleza y Velocidad", 
    activos: "Microchip Internacional", 
    padre: "ARAB-SULTAN", 
    madre: "ARAB-MOON", 
    pesoKg: 460 
  }
];

export const generateAnimals = (count = BASE_ANIMALS.length): Animal[] => {
  if (count <= BASE_ANIMALS.length) {
    return BASE_ANIMALS.slice(0, count);
  }
  const generated: Animal[] = [...BASE_ANIMALS];
  for (let i = BASE_ANIMALS.length + 1; i <= count; i++) {
    const base = BASE_ANIMALS[(i - 1) % BASE_ANIMALS.length];
    generated.push({
      ...base,
      practico: `${base.practico}-${i}`,
      unico: `${base.unico}-${i}`
    });
  }
  return generated;
};

/* =========================================================================
 * MOCK EXPEDIENTES 360 COMPLETOS
 * ========================================================================= */

// Curva de Wood para animal 0001: yt = a * t^b * e^(-c*t)
// a = 16.8, b = 0.26, c = 0.0052
const WOOD_POINTS_0001: CurvaLactanciaPoint[] = [
  { dim: 15, produccionReal: 20.2, produccionWood: 20.4, promedioFinca: 17.5 },
  { dim: 30, produccionReal: 25.4, produccionWood: 25.1, promedioFinca: 20.8 },
  { dim: 45, produccionReal: 28.6, produccionWood: 28.2, promedioFinca: 22.4 },
  { dim: 60, produccionReal: 27.8, produccionWood: 27.5, promedioFinca: 21.9 },
  { dim: 90, produccionReal: 25.2, produccionWood: 25.3, promedioFinca: 20.1 },
  { dim: 120, produccionReal: 23.4, produccionWood: 23.2, promedioFinca: 18.6 },
  { dim: 145, produccionReal: 22.2, produccionWood: 21.8, promedioFinca: 17.4 },
  { dim: 180, produccionWood: 19.8, promedioFinca: 15.9 },
  { dim: 210, produccionWood: 18.2, promedioFinca: 14.8 },
  { dim: 240, produccionWood: 16.7, promedioFinca: 13.6 },
  { dim: 270, produccionWood: 15.1, promedioFinca: 12.5 },
  { dim: 305, produccionWood: 13.4, promedioFinca: 11.2 }
];

export const ANIMAL_360_0001: Animal360 = {
  practico: "0001",
  unico: "VE-01-0001-92",
  rfid: "982.000123849102",
  categoria: "Vaca",
  estatus: "Activo",
  estatusReproductivo: "Preñada",
  diasGestacion: 142,
  estatusProductivo: "Ordeño",
  fechaNacimiento: "15/04/2021",
  edadAnos: 5,
  edadMeses: 5,
  edadTexto: "5 años, 5 meses",
  raza: "Carora (75%) x Holstein (25%)",
  lote: "Lote 01 (Alta Producción)",
  potrero: "Potrero 4 (Pasto Estrella)",
  alias: "MARIPOSA",
  alertaSanitaria: {
    activo: true,
    tipo: 'antibiotico',
    diagnostico: 'Mastitis Clínica Aguda en cuarto Posterior Derecho (PD)',
    farmaco: 'Cefalexina Intramamaria 200mg + Flunixin Meglumine 50mg/ml',
    principioActivo: 'Cefalexina monohidrato + Flunixin meglumina',
    dosis: '1 jeringa intramamaria c/12h x 3 aplicaciones + 10ml IM',
    via: 'Intramamaria',
    cuartosAfectados: ['PD'],
    fechaInicio: '09/09/2026',
    fechaFinRetiroLeche: '15/09/2026',
    diasRestantesLeche: 3,
    fechaFinRetiroCarne: '24/09/2026',
    diasRestantesCarne: 12,
    ordenBloqueoTanque: true,
    veterinario: 'Dr. Ramón Ramírez (MPPS-4821)'
  },
  fotoUrl: '',
  colorPelaje: 'Bayo encerado con mucosas oscuras',
  hierroMarca: {
    codigo: 'H-24',
    posicion: 'Pierna Izquierda',
    tipo: 'Hierro caliente tradicional'
  },
  propietario: 'Agropecuaria El Porvenir, C.A.',
  porcentajeTenencia: 100,
  origen: 'Nacida en Finca (Hato San José)',
  tatuaje: 'Oreja Izq: 0001 | Oreja Der: TAT-092',
  especie: 'Bovino (Bos taurus x Bos indicus)',
  sexo: 'Hembra',
  finalidad: 'Doble Propósito (Lechero Especializado Tropical)',
  notasZootecnicas: 'Vaca élite con 3 lactancias cerradas sobresalientes. Gran adaptabilidad térmica, ubre de inserción fuerte con ligamento medio marcado. En tratamiento resolutivo por mastitis en cuarto PD con bloqueo estricto de tanque.',

  // Genealogía 3 generaciones & Consanguinidad Wright
  pedigri: {
    id: '0001',
    arete: '0001',
    nombre: 'Mariposa',
    raza: 'Carora 75% x Holstein 25%',
    rol: 'Madre',
    padre: {
      id: 'CAR-092',
      arete: 'CAR-092',
      nombre: 'Faraón de Carora',
      raza: 'Carora Puro 100%',
      hba: 'HBA-CA-4402',
      rol: 'Padre',
      padre: {
        id: 'CAR-014',
        arete: 'CAR-014',
        nombre: 'Sultán Negro',
        raza: 'Carora Puro 100%',
        hba: 'HBA-CA-2190',
        rol: 'Abuelo Paterno',
        padre: { id: 'CAR-002', arete: 'CAR-002', nombre: 'Conquistador', raza: 'Carora', rol: 'Bisabuelo' },
        madre: { id: 'CAR-008', arete: 'CAR-008', nombre: 'Reina de Oro', raza: 'Carora', rol: 'Bisabuela' }
      },
      madre: {
        id: 'CAR-065',
        arete: 'CAR-065',
        nombre: 'Princesa 65',
        raza: 'Carora Puro 100%',
        hba: 'HBA-CA-3104',
        rol: 'Abuela Paterna',
        padre: { id: 'CAR-005', arete: 'CAR-005', nombre: 'Centauro', raza: 'Carora', rol: 'Bisabuelo' },
        madre: { id: 'CAR-019', arete: 'CAR-019', nombre: 'Lucero', raza: 'Carora', rol: 'Bisabuela' }
      }
    },
    madre: {
      id: '0045',
      arete: '0045',
      nombre: 'Paloma',
      raza: 'Holstein 50% x Carora 50%',
      hba: 'CR-8831',
      rol: 'Madre',
      padre: {
        id: 'HOL-310',
        arete: 'HOL-310',
        nombre: 'Superstar de Wisconsin',
        raza: 'Holstein 100%',
        hba: 'US-1192834',
        rol: 'Abuelo Materno',
        padre: { id: 'HOL-102', arete: 'HOL-102', nombre: 'Elevation', raza: 'Holstein', rol: 'Bisabuelo' },
        madre: { id: 'HOL-189', arete: 'HOL-189', nombre: 'Bell Linda', raza: 'Holstein', rol: 'Bisabuela' }
      },
      madre: {
        id: '0012',
        arete: '0012',
        nombre: 'Canaria',
        raza: 'Carora Puro 100%',
        hba: 'HBA-CA-1823',
        rol: 'Abuela Materna',
        padre: { id: 'CAR-014', arete: 'CAR-014', nombre: 'Sultán Negro', raza: 'Carora', rol: 'Bisabuelo' },
        madre: { id: '0003', arete: '0003', nombre: 'Margarita', raza: 'Carora', rol: 'Bisabuela' }
      }
    }
  },
  consanguinidad: {
    coeficienteWrightFx: 0.0781, // 7.81%
    alertaEndogamia: true,
    ancestroComun: 'Semental Sultán Negro (CAR-014) presente en línea paterna y materna',
    analisis: 'El coeficiente de consanguinidad de Wright Fx calculado es de 7.81%, superando el umbral zootécnico del 6.25%. Existe riesgo de depresión endogámica (menor vigor híbrido, ligera merma de fertilidad y mayor susceptibilidad a infecciones mamarias).',
    recomendacionCruzamiento: 'Evitar apareamientos con toros emparentados con la línea "Sultán Negro" (CAR-014). Se sugiere utilizar sementales no emparentados de razas divergentes como Girolando F1 o Pardo Suizo importado para maximizar heterosis.'
  },
  desgloseRacial: [
    { raza: 'Carora Tropical', porcentaje: 75, colorHex: '#2d6a4f' },
    { raza: 'Holstein Americano', porcentaje: 25, colorHex: '#52b788' }
  ],

  // Reproductivo
  kpisReproductivos: {
    iepPromedioDias: 382,
    diasAbiertos: 85,
    serviciosPorConcepcion: 1.3,
    devDias: 50,
    totalPartos: 3,
    totalAbortos: 0,
    fechaUltimoParto: '29/10/2025',
    fechaUltimoServicio: '09/03/2026',
    fechaProximoParto: '24/11/2026',
    diasPrenez: 142
  },
  timelineGinecologico: [
    {
      id: 'gyn-1',
      fecha: '23/04/2026',
      campana: 3,
      tipo: 'Palpacion',
      titulo: 'Diagnóstico de Gestación por Ecografía (45 días)',
      descripcion: 'Preñez confirmada. Cuerno grávido derecho con presencia de feto viable con latido cardíaco. Cuerpo lúteo funcional de 22mm en ovario derecho.',
      tecnico: 'Dr. Ramón Ramírez (Veterinario)',
      detalles: {
        diagnosticoEco: 'Preñada Positiva (45d)',
        cuernoUterino: 'Derecho Grávido',
        cuerpoLuteo: 'Ovario Derecho (22mm)'
      }
    },
    {
      id: 'gyn-2',
      fecha: '09/03/2026',
      campana: 3,
      tipo: 'Servicio',
      titulo: 'Inseminación Artificial (IA)',
      descripcion: 'Servicio realizado con semen congelado de CAR-092 (Faraón). Condición cervical grado 3, moco estral cristalino transparente.',
      tecnico: 'Téc. Pedro Mendoza',
      detalles: {
        hora: '07:30 AM',
        toro: 'CAR-092 - Faraón de Carora',
        pajuelaLote: 'LOTE-2025-A',
        metodoServicio: 'IA'
      }
    },
    {
      id: 'gyn-3',
      fecha: '08/03/2026',
      campana: 3,
      tipo: 'Celo',
      titulo: 'Detección de Celo Natural',
      descripcion: 'Celo franco manifestado a las 06:15 AM. Reflejo de inmovilidad positivo ante monta de compañeras. Programada inseminación según regla AM-PM.',
      tecnico: 'Javier Colmenares (Capataz)',
      detalles: { hora: '06:15 AM' }
    },
    {
      id: 'gyn-4',
      fecha: '18/12/2025',
      campana: 3,
      tipo: 'Palpacion',
      titulo: 'Fin de Días de Espera Voluntaria (DEV 50d)',
      descripcion: 'Examen ginecológico post-parto. Involución uterina completa normal. Ovarios en ciclicidad activa sin adherencias.',
      tecnico: 'Dr. Ramón Ramírez',
      detalles: { diagnosticoEco: 'Vientre Apto para Reproducción' }
    },
    {
      id: 'gyn-5',
      fecha: '29/10/2025',
      campana: 2,
      tipo: 'Parto',
      titulo: 'Parto 3 (Eutócico Normal)',
      descripcion: 'Nacimiento de cría hembra viva (38.5 kg, arete BCA-042). Expulsión placentaria a las 2.5 horas sin retención. Inicio de Campaña 3.',
      tecnico: 'Téc. Pedro Mendoza',
      detalles: {
        sexoCria: 'Hembra',
        pesoCriaKg: 38.5,
        areteCria: 'BCA-042',
        tipoParto: 'Eutócico Normal'
      }
    },
    {
      id: 'gyn-6',
      fecha: '28/08/2025',
      campana: 2,
      tipo: 'Secado',
      titulo: 'Secado de Lactancia 2 (305 días)',
      descripcion: 'Cierre formal de la segunda lactancia a los 305 días con 5,680 kg producidos. Aplicación de sellador antimicrobiano intramamario en los 4 pezones.',
      tecnico: 'Dr. Ramón Ramírez',
      detalles: {
        diasLactanciaAcumulados: 305,
        productoSecado: 'Cepravin Secado (Cefalonio)'
      }
    }
  ],

  // Curvas de Lactancia Wood
  lactanciaStats: {
    numeroLactanciaActual: 3,
    diasEnLeche: 145,
    produccionAcumuladaKg: 3280,
    proyeccion305DiasKg: 5840,
    promedioFinca305DiasKg: 4890,
    picoLactanciaKg: 28.6,
    diaPico: 48,
    persistenciaPorc: 92.4,
    grasaMediaPorc: 3.76,
    proteinaMediaPorc: 3.19
  },
  curvaWoodData: WOOD_POINTS_0001,
  controlesLecheros: [
    {
      id: 'cl-1',
      fecha: '10/09/2026',
      dim: 145,
      amKg: 12.8,
      pmKg: 9.4,
      totalKg: 22.2,
      grasaPorc: 3.85,
      proteinaPorc: 3.20,
      ratioGP: 1.20,
      alertaGP: 'Optimo',
      rcs: 320000,
      estatusRCS: 'Alerta Subclínica'
    },
    {
      id: 'cl-2',
      fecha: '25/08/2026',
      dim: 130,
      amKg: 13.5,
      pmKg: 10.1,
      totalKg: 23.6,
      grasaPorc: 3.80,
      proteinaPorc: 3.15,
      ratioGP: 1.21,
      alertaGP: 'Optimo',
      rcs: 145000,
      estatusRCS: 'Normal'
    },
    {
      id: 'cl-3',
      fecha: '10/08/2026',
      dim: 115,
      amKg: 14.1,
      pmKg: 10.6,
      totalKg: 24.7,
      grasaPorc: 3.75,
      proteinaPorc: 3.18,
      ratioGP: 1.18,
      alertaGP: 'Optimo',
      rcs: 130000,
      estatusRCS: 'Normal'
    },
    {
      id: 'cl-4',
      fecha: '25/07/2026',
      dim: 100,
      amKg: 14.8,
      pmKg: 11.2,
      totalKg: 26.0,
      grasaPorc: 3.70,
      proteinaPorc: 3.22,
      ratioGP: 1.15,
      alertaGP: 'Optimo',
      rcs: 125000,
      estatusRCS: 'Normal'
    },
    {
      id: 'cl-5',
      fecha: '10/07/2026',
      dim: 85,
      amKg: 15.6,
      pmKg: 11.8,
      totalKg: 27.4,
      grasaPorc: 3.65,
      proteinaPorc: 3.20,
      ratioGP: 1.14,
      alertaGP: 'Optimo',
      rcs: 110000,
      estatusRCS: 'Normal'
    }
  ],

  // Desarrollo Ponderal
  pesajesAjustados: {
    pesoNacimientoKg: 35,
    pesoAjustado205dKg: 198,
    pesoAjustado365dKg: 320,
    pesoAjustado540dKg: 435,
    pesoActualKg: 560,
    gdpGlobalGramosDia: 742
  },
  historialPesajes: [
    {
      id: 'pes-1',
      fecha: '15/08/2026',
      edadMeses: 64,
      diasVida: 1948,
      pesoKg: 560,
      pesoEsperadoRazaKg: 540,
      gdpPeriodoGramosDia: 380,
      condicionCorporal: 3.25,
      metodo: 'Báscula Electrónica Tru-Test',
      observaciones: 'Buena conformación de costillar y cobertura grasa homogénea.'
    },
    {
      id: 'pes-2',
      fecha: '15/05/2026',
      edadMeses: 61,
      diasVida: 1856,
      pesoKg: 545,
      pesoEsperadoRazaKg: 535,
      gdpPeriodoGramosDia: 420,
      condicionCorporal: 3.00,
      metodo: 'Báscula Electrónica Tru-Test',
      observaciones: 'Tercio inicial de gestación en ordeño.'
    },
    {
      id: 'pes-3',
      fecha: '15/10/2022',
      edadMeses: 18,
      diasVida: 548,
      pesoKg: 435,
      pesoEsperadoRazaKg: 410,
      gdpPeriodoGramosDia: 650,
      condicionCorporal: 3.50,
      metodo: 'Báscula Electrónica Tru-Test',
      observaciones: 'Ajuste estandarizado a los 540 días.'
    },
    {
      id: 'pes-4',
      fecha: '15/04/2022',
      edadMeses: 12,
      diasVida: 365,
      pesoKg: 320,
      pesoEsperadoRazaKg: 300,
      gdpPeriodoGramosDia: 760,
      condicionCorporal: 3.25,
      metodo: 'Báscula Electrónica Tru-Test',
      observaciones: 'Ajuste al año (365 días) superando media racial.'
    },
    {
      id: 'pes-5',
      fecha: '05/11/2021',
      edadMeses: 7,
      diasVida: 205,
      pesoKg: 198,
      pesoEsperadoRazaKg: 180,
      gdpPeriodoGramosDia: 795,
      condicionCorporal: 3.50,
      metodo: 'Báscula Electrónica Tru-Test',
      observaciones: 'Pesaje estandarizado al destete (205 días).'
    }
  ],
  condicionCorporalActual: 3.25,

  // Sanidad y Ubre 4 Cuartos
  cuartosMamarios: {
    AD: {
      codigo: 'AD',
      nombre: 'Anterior Derecho',
      cmt: 'Negativo',
      estadoClinico: 'Sano',
      conductividadMs: 4.6,
      ultimoTratamiento: 'Ninguno'
    },
    AI: {
      codigo: 'AI',
      nombre: 'Anterior Izquierdo',
      cmt: 'Negativo',
      estadoClinico: 'Sano',
      conductividadMs: 4.5,
      ultimoTratamiento: 'Ninguno'
    },
    PD: {
      codigo: 'PD',
      nombre: 'Posterior Derecho',
      cmt: 'Grado 3',
      estadoClinico: 'Mastitis Clínica',
      conductividadMs: 7.8,
      ultimoTratamiento: 'Cefalexina intramamaria 200mg (Día 2/3)'
    },
    PI: {
      codigo: 'PI',
      nombre: 'Posterior Izquierdo',
      cmt: 'Trazas',
      estadoClinico: 'Mastitis Subclínica',
      conductividadMs: 5.2,
      ultimoTratamiento: 'En observación preventiva'
    }
  },
  tratamientosSanitarios: [
    {
      id: 'trat-1',
      fecha: '09/09/2026',
      diagnostico: 'Mastitis Clínica Aguda en cuarto PD',
      farmaco: 'Cefalexina Intramamaria 200mg',
      principioActivo: 'Cefalexina monohidrato',
      dosis: '1 jeringa intramamaria c/12h por 3 aplicaciones',
      via: 'Intramamaria',
      cuartosAfectados: ['PD'],
      retiroLecheHoras: 72,
      retiroCarneDias: 15,
      fechaFinRetiroLeche: '15/09/2026',
      fechaFinRetiroCarne: '24/09/2026',
      diasRestantesRetiro: 3,
      activo: true,
      veterinario: 'Dr. Ramón Ramírez'
    },
    {
      id: 'trat-2',
      fecha: '14/05/2026',
      diagnostico: 'Control Parasitismo Gastrointestinal y Fasciola',
      farmaco: 'Albendazol 10% Oral',
      principioActivo: 'Albendazol sulfóxido',
      dosis: '40 ml vía oral',
      via: 'Oral',
      retiroLecheHoras: 48,
      retiroCarneDias: 14,
      fechaFinRetiroLeche: '16/05/2026',
      fechaFinRetiroCarne: '28/05/2026',
      diasRestantesRetiro: 0,
      activo: false,
      veterinario: 'Dr. Ramón Ramírez'
    }
  ],
  planVacunacion: [
    {
      id: 'vac-1',
      enfermedad: 'Fiebre Aftosa (Bivalente O1/A24)',
      producto: 'Aftogan',
      laboratorio: 'Vecol',
      lote: 'AF-2026-08',
      fechaAplicacion: '15/05/2026',
      fechaProximaDosis: '15/11/2026',
      estado: 'Vigente',
      veterinario: 'Dr. Ramón Ramírez'
    },
    {
      id: 'vac-2',
      enfermedad: 'Brucelosis Bovina (Cepa RB51)',
      producto: 'RB51 Vaccine',
      laboratorio: 'CZ Vaccines',
      lote: 'RB-9812',
      fechaAplicacion: '15/11/2021',
      fechaProximaDosis: 'Permanente (Dosis única)',
      estado: 'Vigente',
      veterinario: 'Dr. Ramón Ramírez'
    },
    {
      id: 'vac-3',
      enfermedad: 'Rabia Paresiante',
      producto: 'Derriengue Vac',
      laboratorio: 'Pronabive',
      lote: 'RP-4410',
      fechaAplicacion: '10/06/2026',
      fechaProximaDosis: '10/06/2027',
      estado: 'Vigente',
      veterinario: 'Dr. Ramón Ramírez'
    },
    {
      id: 'vac-4',
      enfermedad: 'Complejo Reproductivo (IBR, BVD, Lepto 5)',
      producto: 'CattleMaster 4+L5',
      laboratorio: 'Zoetis',
      lote: 'CM-2201',
      fechaAplicacion: '20/01/2026',
      fechaProximaDosis: '20/01/2027',
      estado: 'Vigente',
      veterinario: 'Dr. Ramón Ramírez'
    }
  ],

  // Trazabilidad Espacial
  historialTraslados: [
    {
      id: 'tras-1',
      fechaEntrada: '05/09/2026',
      diasPermanencia: 7,
      potreroId: 'POT-04',
      potreroNombre: 'Potrero 4 - Pasto Estrella',
      hectareas: 4.2,
      tipoPastura: 'Cynodon nlemfuensis (Pasto Estrella Santo Domingo)',
      loteNombre: 'Lote 01 (Alta Producción)',
      cargaAnimalUggHa: 2.8,
      motivo: 'Rotación PRV',
      responsable: 'Javier Colmenares (Capataz)',
      actual: true
    },
    {
      id: 'tras-2',
      fechaEntrada: '28/08/2026',
      fechaSalida: '05/09/2026',
      diasPermanencia: 8,
      potreroId: 'POT-03',
      potreroNombre: 'Potrero 3 - Brachiaria Brizantha',
      hectareas: 5.0,
      tipoPastura: 'Brachiaria brizantha cv. Marandú',
      loteNombre: 'Lote 01 (Alta Producción)',
      cargaAnimalUggHa: 2.4,
      motivo: 'Rotación PRV',
      responsable: 'Javier Colmenares (Capataz)',
      actual: false
    },
    {
      id: 'tras-3',
      fechaEntrada: '20/08/2026',
      fechaSalida: '28/08/2026',
      diasPermanencia: 8,
      potreroId: 'POT-02',
      potreroNombre: 'Potrero 2 - Guinea Mombasa',
      hectareas: 4.8,
      tipoPastura: 'Megathyrsus maximus cv. Mombasa',
      loteNombre: 'Lote 01 (Alta Producción)',
      cargaAnimalUggHa: 2.6,
      motivo: 'Rotación PRV',
      responsable: 'Javier Colmenares (Capataz)',
      actual: false
    },
    {
      id: 'tras-4',
      fechaEntrada: '10/08/2026',
      fechaSalida: '20/08/2026',
      diasPermanencia: 10,
      potreroId: 'POT-01',
      potreroNombre: 'Potrero 1 - Pasto Estrella',
      hectareas: 4.0,
      tipoPastura: 'Cynodon nlemfuensis',
      loteNombre: 'Lote 01 (Alta Producción)',
      cargaAnimalUggHa: 2.7,
      motivo: 'Rotación PRV',
      responsable: 'Javier Colmenares (Capataz)',
      actual: false
    }
  ]
};

// Generador inteligente 360 para cualquier animal del rebaño
export const getAnimal360ByPractico = (practico: string): Animal360 => {
  if (practico === '0001') {
    return ANIMAL_360_0001;
  }

  // Buscar en animales base o generar
  const found = BASE_ANIMALS.find(a => a.practico === practico) || {
    practico,
    unico: `VE-01-${practico}-26`,
    categoria: 'Vaca',
    estatus: 'Activo',
    fechaNacimiento: '16/10/2020',
    edad: '5,9 Años',
    lote: 'Lote 01',
    descripcion: 'Lote 01 - Alta Producción',
    composicion: 'Pardo Suizo 50% x Brahman 50%',
    racial: 'Doble Propósito',
    etiquetas: '',
    activos: 'Arete, RFID',
    padre: 'PS-104',
    madre: 'BR-032'
  };

  const isVaca = found.categoria === 'Vaca';
  const isNovilla = found.categoria === 'Novilla';
  const isBecerra = ['Becerra', 'Becerro'].includes(found.categoria);
  const isToro = found.categoria === 'Toro';

  return {
    ...ANIMAL_360_0001,
    practico: found.practico,
    unico: found.unico || `VE-01-${found.practico}-26`,
    rfid: found.rfid || `982.000123${found.practico.padStart(6, '0')}`,
    especie: found.especie || 'Bovinos',
    categoria: found.categoria,
    subcategoria: found.subcategoria || found.categoria,
    estatus: (found.estatus as any) || 'Activo',
    estatusReproductivo: (found.estatusReproductivo as any) || (isVaca ? 'Preñada' : isNovilla ? 'En espera' : 'Vacía'),
    diasGestacion: found.diasGestacion ?? (isVaca ? 98 : undefined),
    estatusProductivo: (found.estatusProductivo as any) || (isVaca ? 'Ordeño' : isBecerra ? 'Criando' : 'Seca'),
    raza: found.composicion || found.racial || 'Raza Seleccionada',
    lote: found.descripcion || found.lote,
    alias: found.descripcion?.includes(' - ') ? found.descripcion.split(' - ')[1] : `SEMOVIENTE ${found.practico}`,
    alertaSanitaria: found.practico === '0001' ? ANIMAL_360_0001.alertaSanitaria : undefined,
    pesajesAjustados: {
      ...ANIMAL_360_0001.pesajesAjustados,
      pesoActualKg: found.pesoKg || ANIMAL_360_0001.pesajesAjustados.pesoActualKg
    },
    cuartosMamarios: {
      AD: { codigo: 'AD', nombre: 'Anterior Derecho', cmt: 'Negativo', estadoClinico: 'Sano' },
      AI: { codigo: 'AI', nombre: 'Anterior Izquierdo', cmt: 'Negativo', estadoClinico: 'Sano' },
      PD: { codigo: 'PD', nombre: 'Posterior Derecho', cmt: 'Negativo', estadoClinico: 'Sano' },
      PI: { codigo: 'PI', nombre: 'Posterior Izquierdo', cmt: 'Negativo', estadoClinico: 'Sano' }
    },
    consanguinidad: {
      coeficienteWrightFx: 0.0312,
      alertaEndogamia: false,
      analisis: 'El coeficiente de consanguinidad de Wright Fx calculado es de 3.12%, encontrándose dentro de los límites zootécnicos seguros (< 6.25%).',
      recomendacionCruzamiento: 'Animal con excelente vigor híbrido y variabilidad alélica. Apto para programas de reproducción y mejoramiento genético.'
    }
  };
};
