import {
  ReproduccionHistoricoEntity,
  LactanciaHistoricoEntity,
  PesajeLecheHistoricoEntity,
  CrecimientoHistoricoEntity
} from '../../../types2/entities';

/* =========================================================================
 * 1. HISTORIA DE REPRODUCCIONES (/reports/historics/reproductions)
 * ========================================================================= */

export const MOCK_HISTORIA_REPRODUCCIONES: ReproduccionHistoricoEntity[] = [
  {
    practico: '0001',
    unico: '0001',
    categoria: 'Vaca',
    estatus: 'Activo',
    loteActual: '01',
    eventoNumero: 1,
    tipoEvento: 'Parto',
    subtipoEvento: 'Normal',
    fechaEvento: '2026-05-10',
    tecnicoResponsable: 'Dr. Carlos Mendoza',
    machosVivos: 1,
    hembrasVivas: 0,
    reproductor: 'BL001 - Sultán del Valle',
    diagnostico: 'Parto eutócico sin complicaciones',
    tratamiento: 'Aplicación preventiva de antibiótico y vitaminas ADE',
    rebano: 'Rebaño Lechero Principal'
  },
  {
    practico: '0001',
    unico: '0001',
    categoria: 'Vaca',
    estatus: 'Activo',
    loteActual: '01',
    eventoNumero: 2,
    tipoEvento: 'Servicio',
    subtipoEvento: 'Inseminación Artificial',
    fechaEvento: '2026-07-15',
    tecnicoResponsable: 'Ing. Roberto Silva',
    machosVivos: 0,
    hembrasVivas: 0,
    reproductor: 'BL001 - Sultán del Valle',
    diagnostico: 'Celo franco presentado a las 06:00',
    tratamiento: 'Dosis convencional semen congelado',
    rebano: 'Rebaño Lechero Principal'
  },
  {
    practico: 'CW002',
    unico: 'CW002',
    categoria: 'Vaca',
    estatus: 'Activo',
    loteActual: 'ESCT',
    eventoNumero: 1,
    tipoEvento: 'Parto',
    subtipoEvento: 'Normal',
    fechaEvento: '2025-11-14',
    tecnicoResponsable: 'Dra. María Elena Gómez',
    machosVivos: 0,
    hembrasVivas: 1,
    reproductor: 'SM01 - Gyr Lechero',
    diagnostico: 'Parto normal, expulsión de placenta completa',
    tratamiento: 'Oxitetraciclina + Calcio IV',
    rebano: 'Rebaño Lechero Principal'
  },
  {
    practico: 'CW002',
    unico: 'CW002',
    categoria: 'Vaca',
    estatus: 'Activo',
    loteActual: 'ESCT',
    eventoNumero: 2,
    tipoEvento: 'Revisión',
    subtipoEvento: 'Palpación Rectal',
    fechaEvento: '2026-07-15',
    tecnicoResponsable: 'Dr. Carlos Mendoza',
    machosVivos: 0,
    hembrasVivas: 0,
    diagnostico: 'Cuerpo lúteo funcional ovario derecho',
    tratamiento: 'Programación para IATF',
    rebano: 'Rebaño Lechero Principal'
  },
  {
    practico: 'CW002',
    unico: 'CW002',
    categoria: 'Vaca',
    estatus: 'Activo',
    loteActual: 'ESCT',
    eventoNumero: 3,
    tipoEvento: 'Servicio',
    subtipoEvento: 'Inseminación Artificial (IATF)',
    fechaEvento: '2026-08-02',
    tecnicoResponsable: 'Ing. Roberto Silva',
    machosVivos: 0,
    hembrasVivas: 0,
    reproductor: 'SM02 - Brahman Rojo',
    diagnostico: 'Inseminación a tiempo fijo con buena respuesta',
    tratamiento: 'Retiro de dispositivo de progesterona + GnRH',
    rebano: 'Rebaño Lechero Principal'
  },
  {
    practico: 'CW003',
    unico: 'CW003',
    categoria: 'Vaca',
    estatus: 'Activo',
    loteActual: 'SEC1',
    eventoNumero: 1,
    tipoEvento: 'Parto',
    subtipoEvento: 'Normal',
    fechaEvento: '2025-08-30',
    tecnicoResponsable: 'Dr. Carlos Mendoza',
    machosVivos: 1,
    hembrasVivas: 0,
    reproductor: 'BL001 - Sultán del Valle',
    diagnostico: 'Parto sin dificultades',
    rebano: 'Rebaño Lechero Principal'
  },
  {
    practico: 'CW003',
    unico: 'CW003',
    categoria: 'Vaca',
    estatus: 'Activo',
    loteActual: 'SEC1',
    eventoNumero: 2,
    tipoEvento: 'Servicio',
    subtipoEvento: 'Inseminación Artificial',
    fechaEvento: '2025-12-10',
    tecnicoResponsable: 'Ing. Roberto Silva',
    machosVivos: 0,
    hembrasVivas: 0,
    reproductor: 'BL001 - Sultán del Valle',
    rebano: 'Rebaño Lechero Principal'
  },
  {
    practico: 'CW003',
    unico: 'CW003',
    categoria: 'Vaca',
    estatus: 'Activo',
    loteActual: 'SEC1',
    eventoNumero: 3,
    tipoEvento: 'Revisión',
    subtipoEvento: 'Ecografía',
    fechaEvento: '2026-01-25',
    tecnicoResponsable: 'Dr. Carlos Mendoza',
    machosVivos: 0,
    hembrasVivas: 0,
    diagnostico: 'Gestación confirmada 46 días',
    rebano: 'Rebaño Lechero Principal'
  },
  {
    practico: 'CW004',
    unico: 'CW004',
    categoria: 'Vaca',
    estatus: 'Activo',
    loteActual: 'ESCT',
    eventoNumero: 1,
    tipoEvento: 'Parto',
    subtipoEvento: 'Normal',
    fechaEvento: '2026-01-20',
    tecnicoResponsable: 'Dra. María Elena Gómez',
    machosVivos: 0,
    hembrasVivas: 1,
    reproductor: 'SM01 - Gyr Lechero',
    diagnostico: 'Cría hembra vigorosa',
    rebano: 'Rebaño Lechero Principal'
  },
  {
    practico: 'CW004',
    unico: 'CW004',
    categoria: 'Vaca',
    estatus: 'Activo',
    loteActual: 'ESCT',
    eventoNumero: 2,
    tipoEvento: 'Servicio',
    subtipoEvento: 'Monta Natural',
    fechaEvento: '2026-04-12',
    tecnicoResponsable: 'Ing. Roberto Silva',
    machosVivos: 0,
    hembrasVivas: 0,
    reproductor: 'SM01 - Gyr Lechero',
    rebano: 'Rebaño Lechero Principal'
  },
  {
    practico: 'CW005',
    unico: 'CW005',
    categoria: 'Vaca',
    estatus: 'Activo',
    loteActual: 'ESCT',
    eventoNumero: 1,
    tipoEvento: 'Parto',
    subtipoEvento: 'Normal',
    fechaEvento: '2026-02-18',
    tecnicoResponsable: 'Dr. Carlos Mendoza',
    machosVivos: 1,
    hembrasVivas: 0,
    reproductor: 'BL002 - Rey Criollo',
    diagnostico: 'Parto matutino favorable',
    rebano: 'Rebaño Lechero Principal'
  },
  {
    practico: 'CW006',
    unico: 'CW006',
    categoria: 'Vaca',
    estatus: 'Activo',
    loteActual: 'ESCT',
    eventoNumero: 1,
    tipoEvento: 'Parto',
    subtipoEvento: 'Asistido',
    fechaEvento: '2026-03-05',
    tecnicoResponsable: 'Dr. Carlos Mendoza',
    machosVivos: 1,
    hembrasVivas: 0,
    reproductor: 'SM02 - Brahman Rojo',
    diagnostico: 'Distocia leve por presentación posterior',
    tratamiento: 'Tracción manual asistida y analgésicos',
    rebano: 'Rebaño Lechero Principal'
  },
  {
    practico: 'CW013',
    unico: 'CW013',
    categoria: 'Novilla',
    estatus: 'Activo',
    loteActual: 'ESCT',
    eventoNumero: 1,
    tipoEvento: 'Celo',
    subtipoEvento: 'Natural',
    fechaEvento: '2026-07-24',
    tecnicoResponsable: 'Ing. Roberto Silva',
    machosVivos: 0,
    hembrasVivas: 0,
    diagnostico: 'Celo visible, moco transparente',
    rebano: 'Rebaño Lechero Principal'
  },
  {
    practico: 'CW013',
    unico: 'CW013',
    categoria: 'Novilla',
    estatus: 'Activo',
    loteActual: 'ESCT',
    eventoNumero: 2,
    tipoEvento: 'Servicio',
    subtipoEvento: 'Inseminación Artificial',
    fechaEvento: '2026-08-15',
    tecnicoResponsable: 'Ing. Roberto Silva',
    machosVivos: 0,
    hembrasVivas: 0,
    reproductor: 'SM01 - Gyr Lechero',
    diagnostico: 'Primer servicio para novilla en condición corporal 3.5',
    rebano: 'Rebaño Lechero Principal'
  }
];

/* =========================================================================
 * 2. HISTORIA DE LACTANCIAS (/reports/historics/lactations)
 * ========================================================================= */

export const MOCK_HISTORIA_LACTANCIAS: LactanciaHistoricoEntity[] = [
  {
    practico: '0001',
    unico: '0001',
    categoria: 'Vaca',
    estatus: 'Activo',
    loteActual: '01',
    fecha: '2025-04-12',
    lactanciaNumero: 5,
    diasLactancia: 305,
    p244Kg: 4120,
    p270Kg: 4450,
    p305Kg: 4890,
    produccionTotalKg: 4920,
    rebano: 'Rebaño Lechero Principal'
  },
  {
    practico: '0001',
    unico: '0001',
    categoria: 'Vaca',
    estatus: 'Activo',
    loteActual: '01',
    fecha: '2026-05-10',
    lactanciaNumero: 6,
    diasLactancia: 124,
    p244Kg: 2150,
    p270Kg: 2150,
    p305Kg: 2150,
    produccionTotalKg: 2150,
    rebano: 'Rebaño Lechero Principal'
  },
  {
    practico: '0002',
    unico: '0002',
    categoria: 'Vaca',
    estatus: 'Activo',
    loteActual: '01',
    fecha: '2024-12-01',
    lactanciaNumero: 4,
    diasLactancia: 310,
    p244Kg: 4600,
    p270Kg: 5010,
    p305Kg: 5420,
    produccionTotalKg: 5500,
    rebano: 'Rebaño Lechero Principal'
  },
  {
    practico: '0002',
    unico: '0002',
    categoria: 'Vaca',
    estatus: 'Activo',
    loteActual: '01',
    fecha: '2026-03-22',
    lactanciaNumero: 5,
    diasLactancia: 173,
    p244Kg: 3100,
    p270Kg: 3100,
    p305Kg: 3100,
    produccionTotalKg: 3100,
    rebano: 'Rebaño Lechero Principal'
  },
  {
    practico: 'CW002',
    unico: 'CW002',
    categoria: 'Vaca',
    estatus: 'Activo',
    loteActual: 'ESCT',
    fecha: '2025-11-14',
    lactanciaNumero: 4,
    diasLactancia: 301,
    p244Kg: 3850,
    p270Kg: 4180,
    p305Kg: 4520,
    produccionTotalKg: 4520,
    rebano: 'Rebaño Lechero Principal'
  },
  {
    practico: 'CW003',
    unico: 'CW003',
    categoria: 'Vaca',
    estatus: 'Activo',
    loteActual: 'SEC1',
    fecha: '2025-08-30',
    lactanciaNumero: 4,
    diasLactancia: 290,
    p244Kg: 4210,
    p270Kg: 4580,
    p305Kg: 4760,
    produccionTotalKg: 4760,
    rebano: 'Rebaño Lechero Principal'
  },
  {
    practico: 'CW007',
    unico: 'CW007',
    categoria: 'Vaca',
    estatus: 'Activo',
    loteActual: 'SEC1',
    fecha: '2025-06-12',
    lactanciaNumero: 3,
    diasLactancia: 270,
    p244Kg: 3450,
    p270Kg: 3720,
    p305Kg: 3720,
    produccionTotalKg: 3720,
    rebano: 'Rebaño Lechero Principal'
  },
  {
    practico: 'CW008',
    unico: 'CW008',
    categoria: 'Vaca',
    estatus: 'Activo',
    loteActual: 'ESCT',
    fecha: '2025-10-08',
    lactanciaNumero: 4,
    diasLactancia: 338,
    p244Kg: 4980,
    p270Kg: 5390,
    p305Kg: 5850,
    produccionTotalKg: 6150,
    rebano: 'Rebaño Lechero Principal'
  },
  {
    practico: 'CW010',
    unico: 'CW010',
    categoria: 'Vaca',
    estatus: 'Activo',
    loteActual: 'ESCT',
    fecha: '2025-12-05',
    lactanciaNumero: 2,
    diasLactancia: 280,
    p244Kg: 3620,
    p270Kg: 3910,
    p305Kg: 4050,
    produccionTotalKg: 4050,
    rebano: 'Rebaño Lechero Principal'
  },
  {
    practico: 'VC-88',
    unico: 'VC-88',
    categoria: 'Vaca',
    estatus: 'Activo',
    loteActual: '01',
    fecha: '2025-11-20',
    lactanciaNumero: 3,
    diasLactancia: 295,
    p244Kg: 4300,
    p270Kg: 4680,
    p305Kg: 5020,
    produccionTotalKg: 5020,
    rebano: 'Rebaño Lechero Principal'
  }
];

/* =========================================================================
 * 3. HISTORIA DE PESAJES DE LECHE (/reports/historics/milks)
 * ========================================================================= */

export const MOCK_HISTORIA_PESAJES_LECHE: PesajeLecheHistoricoEntity[] = [
  {
    practico: '0002',
    unico: '0002',
    categoria: 'Vaca',
    estatus: 'Activo',
    loteActual: '01',
    fecha: '2026-09-01',
    lactanciaNumero: 5,
    tipoPesaje: 'Ordeño',
    pesaje1Kg: 8.5,
    pesaje2Kg: 6.8,
    pesaje3Kg: 0,
    pesajeTotalKg: 15.3,
    comentario: 'Control mensual ordinario'
  },
  {
    practico: '0002',
    unico: '0002',
    categoria: 'Vaca',
    estatus: 'Activo',
    loteActual: '01',
    fecha: '2026-08-01',
    lactanciaNumero: 5,
    tipoPesaje: 'Ordeño',
    pesaje1Kg: 9.2,
    pesaje2Kg: 7.1,
    pesaje3Kg: 0,
    pesajeTotalKg: 16.3,
    comentario: 'Buena persistencia'
  },
  {
    practico: 'CW002',
    unico: 'CW002',
    categoria: 'Vaca',
    estatus: 'Activo',
    loteActual: 'ESCT',
    fecha: '2026-09-01',
    lactanciaNumero: 4,
    tipoPesaje: 'Ordeño',
    pesaje1Kg: 6.4,
    pesaje2Kg: 5.2,
    pesaje3Kg: 0,
    pesajeTotalKg: 11.6,
    comentario: 'Fase final de lactancia'
  },
  {
    practico: 'CW008',
    unico: 'CW008',
    categoria: 'Vaca',
    estatus: 'Activo',
    loteActual: 'ESCT',
    fecha: '2026-09-01',
    lactanciaNumero: 4,
    tipoPesaje: 'Ordeño',
    pesaje1Kg: 7.8,
    pesaje2Kg: 6.4,
    pesaje3Kg: 0,
    pesajeTotalKg: 14.2,
    comentario: 'Producción sostenida'
  },
  {
    practico: 'CW009',
    unico: 'CW009',
    categoria: 'Vaca',
    estatus: 'Activo',
    loteActual: 'ESCT',
    fecha: '2026-09-01',
    lactanciaNumero: 3,
    tipoPesaje: 'Ordeño',
    pesaje1Kg: 8.0,
    pesaje2Kg: 6.6,
    pesaje3Kg: 0,
    pesajeTotalKg: 14.6,
    comentario: 'Muy buena producción pico'
  },
  {
    practico: 'CW010',
    unico: 'CW010',
    categoria: 'Vaca',
    estatus: 'Activo',
    loteActual: 'ESCT',
    fecha: '2026-09-01',
    lactanciaNumero: 2,
    tipoPesaje: 'Ordeño',
    pesaje1Kg: 5.3,
    pesaje2Kg: 4.1,
    pesaje3Kg: 0,
    pesajeTotalKg: 9.4,
    comentario: 'Próxima a secar'
  },
  {
    practico: 'VC-88',
    unico: 'VC-88',
    categoria: 'Vaca',
    estatus: 'Activo',
    loteActual: '01',
    fecha: '2026-09-01',
    lactanciaNumero: 3,
    tipoPesaje: 'Ordeño',
    pesaje1Kg: 4.8,
    pesaje2Kg: 3.4,
    pesaje3Kg: 0,
    pesajeTotalKg: 8.2,
    comentario: 'Descenso fisiológico previo a secado'
  },
  {
    practico: 'VC-92',
    unico: 'VC-92',
    categoria: 'Vaca',
    estatus: 'Activo',
    loteActual: '01',
    fecha: '2026-09-01',
    lactanciaNumero: 2,
    tipoPesaje: 'Ordeño',
    pesaje1Kg: 9.5,
    pesaje2Kg: 7.9,
    pesaje3Kg: 0,
    pesajeTotalKg: 17.4,
    comentario: 'Máxima producción del lote 01'
  }
];

/* =========================================================================
 * 4. HISTORIA DE CRECIMIENTOS (/reports/historics/weighings)
 * ========================================================================= */

export const MOCK_HISTORIA_CRECIMIENTOS: CrecimientoHistoricoEntity[] = [
  {
    practico: 'BC-101',
    unico: 'VE-2026-101',
    categoria: 'Becerro',
    estatus: 'Activo',
    loteActual: '01',
    fecha: '2026-05-10',
    tipoPesaje: 'Al nacer',
    pesoKg: 36,
    gananciaGramosDia: 0,
    alturaMetros: 0.72,
    diasEntreFechas: 0,
    tecnicoResponsable: 'Dr. Carlos Mendoza'
  },
  {
    practico: 'BC-101',
    unico: 'VE-2026-101',
    categoria: 'Becerro',
    estatus: 'Activo',
    loteActual: '01',
    fecha: '2026-07-10',
    tipoPesaje: 'General',
    pesoKg: 78,
    gananciaGramosDia: 688,
    alturaMetros: 0.85,
    gananciaCmDia: 0.21,
    diasEntreFechas: 61,
    tecnicoResponsable: 'Dr. Carlos Mendoza'
  },
  {
    practico: 'BC-101',
    unico: 'VE-2026-101',
    categoria: 'Becerro',
    estatus: 'Activo',
    loteActual: '01',
    fecha: '2026-09-05',
    tipoPesaje: 'General',
    pesoKg: 118,
    gananciaGramosDia: 701,
    alturaMetros: 0.94,
    gananciaCmDia: 0.16,
    diasEntreFechas: 57,
    tecnicoResponsable: 'Ing. Roberto Silva'
  },
  {
    practico: 'BR-01',
    unico: 'VE-2026-BR01',
    categoria: 'Becerra',
    estatus: 'Activo',
    loteActual: 'POT1',
    fecha: '2026-01-20',
    tipoPesaje: 'Al nacer',
    pesoKg: 32,
    gananciaGramosDia: 0,
    alturaMetros: 0.70,
    diasEntreFechas: 0,
    tecnicoResponsable: 'Dra. María Elena Gómez'
  },
  {
    practico: 'BR-01',
    unico: 'VE-2026-BR01',
    categoria: 'Becerra',
    estatus: 'Activo',
    loteActual: 'POT1',
    fecha: '2026-06-20',
    tipoPesaje: 'Al destete',
    pesoKg: 145,
    gananciaGramosDia: 748,
    alturaMetros: 0.96,
    gananciaCmDia: 0.17,
    diasEntreFechas: 151,
    tecnicoResponsable: 'Dr. Carlos Mendoza'
  },
  {
    practico: 'BR-01',
    unico: 'VE-2026-BR01',
    categoria: 'Becerra',
    estatus: 'Activo',
    loteActual: 'POT1',
    fecha: '2026-08-30',
    tipoPesaje: 'General',
    pesoKg: 198,
    gananciaGramosDia: 746,
    alturaMetros: 1.08,
    gananciaCmDia: 0.17,
    diasEntreFechas: 71,
    tecnicoResponsable: 'Dr. Carlos Mendoza'
  },
  {
    practico: 'MT-01',
    unico: 'VE-2025-MT01',
    categoria: 'Maute',
    estatus: 'Activo',
    loteActual: 'ESCT',
    fecha: '2025-06-15',
    tipoPesaje: 'Al nacer',
    pesoKg: 38,
    gananciaGramosDia: 0,
    alturaMetros: 0.75,
    diasEntreFechas: 0,
    tecnicoResponsable: 'Dr. Carlos Mendoza'
  },
  {
    practico: 'MT-01',
    unico: 'VE-2025-MT01',
    categoria: 'Maute',
    estatus: 'Activo',
    loteActual: 'ESCT',
    fecha: '2026-05-15',
    tipoPesaje: 'General',
    pesoKg: 285,
    gananciaGramosDia: 739,
    alturaMetros: 1.18,
    gananciaCmDia: 0.13,
    diasEntreFechas: 334,
    tecnicoResponsable: 'Ing. Roberto Silva'
  },
  {
    practico: 'MT-01',
    unico: 'VE-2025-MT01',
    categoria: 'Maute',
    estatus: 'Activo',
    loteActual: 'ESCT',
    fecha: '2026-08-20',
    tipoPesaje: 'General',
    pesoKg: 345,
    gananciaGramosDia: 618,
    alturaMetros: 1.25,
    gananciaCmDia: 0.07,
    diasEntreFechas: 97,
    tecnicoResponsable: 'Ing. Roberto Silva'
  },
  {
    practico: 'MA-05',
    unico: 'VE-2025-MA05',
    categoria: 'Mauta',
    estatus: 'Activo',
    loteActual: 'ESCT',
    fecha: '2025-05-10',
    tipoPesaje: 'Al nacer',
    pesoKg: 34,
    gananciaGramosDia: 0,
    alturaMetros: 0.73,
    diasEntreFechas: 0,
    tecnicoResponsable: 'Dra. María Elena Gómez'
  },
  {
    practico: 'MA-05',
    unico: 'VE-2025-MA05',
    categoria: 'Mauta',
    estatus: 'Activo',
    loteActual: 'ESCT',
    fecha: '2026-04-10',
    tipoPesaje: 'General',
    pesoKg: 260,
    gananciaGramosDia: 674,
    alturaMetros: 1.15,
    gananciaCmDia: 0.12,
    diasEntreFechas: 335,
    tecnicoResponsable: 'Dr. Carlos Mendoza'
  },
  {
    practico: 'MA-05',
    unico: 'VE-2025-MA05',
    categoria: 'Mauta',
    estatus: 'Activo',
    loteActual: 'ESCT',
    fecha: '2026-08-15',
    tipoPesaje: 'Al servicio',
    pesoKg: 322,
    gananciaGramosDia: 488,
    alturaMetros: 1.22,
    gananciaCmDia: 0.05,
    diasEntreFechas: 127,
    tecnicoResponsable: 'Dr. Carlos Mendoza'
  },
  {
    practico: 'NV-02',
    unico: 'VE-2024-NV02',
    categoria: 'Novillo',
    estatus: 'Activo',
    loteActual: 'ESCT',
    fecha: '2026-08-25',
    tipoPesaje: 'General',
    pesoKg: 468,
    gananciaGramosDia: 552,
    alturaMetros: 1.38,
    gananciaCmDia: 0.04,
    diasEntreFechas: 105,
    tecnicoResponsable: 'Dr. Carlos Mendoza'
  }
];
