import {
  VientreEntity,
  ProximaSecarEntity,
  ProximaParirEntity,
  ProximaRevisarEntity,
  AnimalSecoEntity,
  AnimalLactandoEntity,
  AnimalCriandoEntity,
  NoVientreEntity
} from '../../../types2/entities';

/* =========================================================================
 * 1. DATOS DE VIENTRES (/reports/dams)
 * Basado en los semovientes del rebaño de prueba de GanSoft
 * ========================================================================= */

export const MOCK_VIENTRES: VientreEntity[] = [
  {
    practico: '0001',
    unico: '0001',
    categoria: 'Vaca',
    estatus: 'Activo',
    estatusReproductivo: 'Vacía',
    estatusProductivo: 'Criando',
    lote: '01',
    edadAnos: 17.91,
    partos: 6,
    ultimoPartoAborto: '2026-05-10',
    ultimoServicio: '2026-07-15',
    reproductor: 'BL001 - Sultán del Valle'
  },
  {
    practico: '0002',
    unico: '0002',
    categoria: 'Vaca',
    estatus: 'Activo',
    estatusReproductivo: 'Vacía',
    estatusProductivo: 'Ordeño',
    lote: '01',
    edadAnos: 16.90,
    partos: 5,
    ultimoPartoAborto: '2026-03-22',
    ultimoServicio: '2026-06-18',
    reproductor: 'SM01 - Gyr Lechero'
  },
  {
    practico: 'CW002',
    unico: 'CW002',
    categoria: 'Vaca',
    estatus: 'Activo',
    estatusReproductivo: 'En espera',
    estatusProductivo: 'Ordeño',
    lote: 'ESCT',
    edadAnos: 11.90,
    partos: 4,
    ultimoPartoAborto: '2025-11-14',
    ultimoServicio: '2026-08-02',
    reproductor: 'SM02 - Brahman Rojo'
  },
  {
    practico: 'CW003',
    unico: 'CW003',
    categoria: 'Vaca',
    estatus: 'Activo',
    estatusReproductivo: 'Preñada',
    estatusProductivo: 'Seca',
    lote: 'SEC1',
    edadAnos: 12.57,
    partos: 4,
    ultimoPartoAborto: '2025-08-30',
    ultimoServicio: '2025-12-10',
    reproductor: 'BL001 - Sultán del Valle'
  },
  {
    practico: 'CW004',
    unico: 'CW004',
    categoria: 'Vaca',
    estatus: 'Activo',
    estatusReproductivo: 'Preñada',
    estatusProductivo: 'Criando',
    lote: 'ESCT',
    edadAnos: 12.90,
    partos: 3,
    ultimoPartoAborto: '2026-01-20',
    ultimoServicio: '2026-04-12',
    reproductor: 'SM01 - Gyr Lechero'
  },
  {
    practico: 'CW005',
    unico: 'CW005',
    categoria: 'Vaca',
    estatus: 'Activo',
    estatusReproductivo: 'Vacía',
    estatusProductivo: 'Criando',
    lote: 'ESCT',
    edadAnos: 12.90,
    partos: 3,
    ultimoPartoAborto: '2026-02-18',
    ultimoServicio: '2026-06-25',
    reproductor: 'BL002 - Rey Criollo'
  },
  {
    practico: 'CW006',
    unico: 'CW006',
    categoria: 'Vaca',
    estatus: 'Activo',
    estatusReproductivo: 'En espera',
    estatusProductivo: 'Criando',
    lote: 'ESCT',
    edadAnos: 11.82,
    partos: 3,
    ultimoPartoAborto: '2026-03-05',
    ultimoServicio: '2026-07-28',
    reproductor: 'SM02 - Brahman Rojo'
  },
  {
    practico: 'CW007',
    unico: 'CW007',
    categoria: 'Vaca',
    estatus: 'Activo',
    estatusReproductivo: 'Vacía',
    estatusProductivo: 'Seca',
    lote: 'SEC1',
    edadAnos: 11.47,
    partos: 3,
    ultimoPartoAborto: '2025-06-12',
    ultimoServicio: '2026-05-14',
    reproductor: 'BL001 - Sultán del Valle'
  },
  {
    practico: 'CW008',
    unico: 'CW008',
    categoria: 'Vaca',
    estatus: 'Activo',
    estatusReproductivo: 'Vacía',
    estatusProductivo: 'Ordeño',
    lote: 'ESCT',
    edadAnos: 12.39,
    partos: 4,
    ultimoPartoAborto: '2025-10-08',
    ultimoServicio: '2026-07-02',
    reproductor: 'SM01 - Gyr Lechero'
  },
  {
    practico: 'CW009',
    unico: 'CW009',
    categoria: 'Vaca',
    estatus: 'Activo',
    estatusReproductivo: 'Vacía',
    estatusProductivo: 'Ordeño',
    lote: 'ESCT',
    edadAnos: 11.90,
    partos: 3,
    ultimoPartoAborto: '2026-01-15',
    ultimoServicio: '2026-06-10',
    reproductor: 'BL002 - Rey Criollo'
  },
  {
    practico: 'CW010',
    unico: 'CW010',
    categoria: 'Vaca',
    estatus: 'Activo',
    estatusReproductivo: 'Preñada',
    estatusProductivo: 'Ordeño',
    lote: 'ESCT',
    edadAnos: 10.50,
    partos: 2,
    ultimoPartoAborto: '2025-12-05',
    ultimoServicio: '2026-03-15',
    reproductor: 'BL001 - Sultán del Valle'
  },
  {
    practico: 'CW011',
    unico: 'CW011',
    categoria: 'Vaca',
    estatus: 'Activo',
    estatusReproductivo: 'Vacía',
    estatusProductivo: 'Criando',
    lote: 'ESCT',
    edadAnos: 10.20,
    partos: 2,
    ultimoPartoAborto: '2026-04-10',
    ultimoServicio: '2026-08-11',
    reproductor: 'SM02 - Brahman Rojo'
  },
  {
    practico: 'CW012',
    unico: 'CW012',
    categoria: 'Vaca',
    estatus: 'Activo',
    estatusReproductivo: 'Vacía',
    estatusProductivo: 'Seca',
    lote: 'SEC1',
    edadAnos: 11.10,
    partos: 3,
    ultimoPartoAborto: '2025-05-18',
    ultimoServicio: '2026-04-20',
    reproductor: 'BL001 - Sultán del Valle'
  },
  {
    practico: 'CW013',
    unico: 'CW013',
    categoria: 'Novilla',
    estatus: 'Activo',
    estatusReproductivo: 'En espera',
    estatusProductivo: 'Seca',
    lote: 'ESCT',
    edadAnos: 2.80,
    partos: 0,
    ultimoPartoAborto: undefined,
    ultimoServicio: '2026-08-15',
    reproductor: 'SM01 - Gyr Lechero'
  },
  {
    practico: 'CW014',
    unico: 'CW014',
    categoria: 'Vaca',
    estatus: 'Activo',
    estatusReproductivo: 'Vacía',
    estatusProductivo: 'Criando',
    lote: 'ESCT',
    edadAnos: 9.80,
    partos: 2,
    ultimoPartoAborto: '2026-04-28',
    ultimoServicio: '2026-07-20',
    reproductor: 'BL002 - Rey Criollo'
  },
  {
    practico: 'CW015',
    unico: 'CW015',
    categoria: 'Novilla',
    estatus: 'Activo',
    estatusReproductivo: 'Preñada',
    estatusProductivo: 'Seca',
    lote: 'ESCT',
    edadAnos: 2.95,
    partos: 0,
    ultimoPartoAborto: undefined,
    ultimoServicio: '2026-02-10',
    reproductor: 'BL001 - Sultán del Valle'
  },
  {
    practico: 'CW001BBB',
    unico: 'CW001BBB',
    categoria: 'Vaca',
    estatus: 'Activo',
    estatusReproductivo: 'Vacía',
    estatusProductivo: 'Seca',
    lote: 'SEC1',
    edadAnos: 13.10,
    partos: 4,
    ultimoPartoAborto: '2025-07-22',
    ultimoServicio: '2026-05-30',
    reproductor: 'SM02 - Brahman Rojo'
  },
  {
    practico: 'NV-201',
    unico: 'NV-201',
    categoria: 'Novilla',
    estatus: 'Activo',
    estatusReproductivo: 'Vacía',
    estatusProductivo: 'Seca',
    lote: 'ESCT',
    edadAnos: 2.45,
    partos: 0,
    ultimoPartoAborto: undefined,
    ultimoServicio: '2026-06-12',
    reproductor: 'SM01 - Gyr Lechero'
  },
  {
    practico: 'VC-88',
    unico: 'VC-88',
    categoria: 'Vaca',
    estatus: 'Activo',
    estatusReproductivo: 'Preñada',
    estatusProductivo: 'Ordeño',
    lote: '01',
    edadAnos: 8.50,
    partos: 3,
    ultimoPartoAborto: '2025-11-20',
    ultimoServicio: '2026-02-25',
    reproductor: 'BL001 - Sultán del Valle'
  },
  {
    practico: 'VC-92',
    unico: 'VC-92',
    categoria: 'Vaca',
    estatus: 'Activo',
    estatusReproductivo: 'Vacía',
    estatusProductivo: 'Ordeño',
    lote: '01',
    edadAnos: 7.90,
    partos: 2,
    ultimoPartoAborto: '2026-02-01',
    ultimoServicio: '2026-05-18',
    reproductor: 'BL002 - Rey Criollo',
    especie: 'Bovinos'
  },
  // BÚFALOS
  {
    practico: 'BUF-01',
    unico: 'BUF-0001',
    categoria: 'Búfala',
    especie: 'Búfalos',
    estatus: 'Activo',
    estatusReproductivo: 'Preñada',
    estatusProductivo: 'Ordeño',
    lote: 'BUF-01',
    edadAnos: 6.5,
    partos: 3,
    ultimoPartoAborto: '2025-10-15',
    ultimoServicio: '2025-11-20',
    reproductor: 'PAD-BUF01 Murrah'
  },
  {
    practico: 'BUF-02',
    unico: 'BUF-0002',
    categoria: 'Búfala',
    especie: 'Búfalos',
    estatus: 'Activo',
    estatusReproductivo: 'Vacía',
    estatusProductivo: 'Ordeño',
    lote: 'BUF-01',
    edadAnos: 5.2,
    partos: 2,
    ultimoPartoAborto: '2026-02-12',
    ultimoServicio: '2026-06-10',
    reproductor: 'PAD-BUF02 Mediterráneo'
  },
  {
    practico: 'BUF-03',
    unico: 'BUF-0003',
    categoria: 'Bubilla',
    especie: 'Búfalos',
    estatus: 'Activo',
    estatusReproductivo: 'Preñada',
    estatusProductivo: 'Seca',
    lote: 'BUF-01',
    edadAnos: 2.8,
    partos: 0,
    ultimoPartoAborto: undefined,
    ultimoServicio: '2026-01-10',
    reproductor: 'PAD-BUF01 Murrah'
  },
  // PORCINOS
  {
    practico: 'POR-101',
    unico: 'POR-0101',
    categoria: 'Cerda Reproductora',
    especie: 'Porcinos',
    estatus: 'Activo',
    estatusReproductivo: 'Preñada',
    estatusProductivo: 'Seca',
    lote: 'PIARA-01',
    edadAnos: 2.4,
    partos: 3,
    ultimoPartoAborto: '2026-05-18',
    ultimoServicio: '2026-06-01',
    reproductor: 'VER-01 Pietrain Duroc'
  },
  {
    practico: 'POR-102',
    unico: 'POR-0102',
    categoria: 'Cerda Reproductora',
    especie: 'Porcinos',
    estatus: 'Activo',
    estatusReproductivo: 'Vacía',
    estatusProductivo: 'Lactancia',
    lote: 'PIARA-01',
    edadAnos: 1.9,
    partos: 2,
    ultimoPartoAborto: '2026-08-25',
    ultimoServicio: undefined,
    reproductor: 'VER-02 Landrace'
  },
  {
    practico: 'POR-103',
    unico: 'POR-0103',
    categoria: 'Cerda de Reemplazo',
    especie: 'Porcinos',
    estatus: 'Activo',
    estatusReproductivo: 'En espera',
    estatusProductivo: 'Seca',
    lote: 'PIARA-01',
    edadAnos: 0.8,
    partos: 0,
    ultimoPartoAborto: undefined,
    ultimoServicio: '2026-08-28',
    reproductor: 'VER-01 Pietrain Duroc'
  },
  // CAPRINOS
  {
    practico: 'CAP-201',
    unico: 'CAP-0201',
    categoria: 'Cabra Lechera',
    especie: 'Caprinos',
    estatus: 'Activo',
    estatusReproductivo: 'Preñada',
    estatusProductivo: 'Ordeño',
    lote: 'APR-01',
    edadAnos: 3.8,
    partos: 3,
    ultimoPartoAborto: '2025-12-10',
    ultimoServicio: '2026-04-28',
    reproductor: 'CHV-01 Saanen Puro'
  },
  {
    practico: 'CAP-202',
    unico: 'CAP-0202',
    categoria: 'Cabra Lechera',
    especie: 'Caprinos',
    estatus: 'Activo',
    estatusReproductivo: 'Vacía',
    estatusProductivo: 'Ordeño',
    lote: 'APR-01',
    edadAnos: 2.9,
    partos: 2,
    ultimoPartoAborto: '2026-03-14',
    ultimoServicio: '2026-07-05',
    reproductor: 'CHV-02 Alpino Francés'
  },
  {
    practico: 'CAP-203',
    unico: 'CAP-0203',
    categoria: 'Cabritona',
    especie: 'Caprinos',
    estatus: 'Activo',
    estatusReproductivo: 'Preñada',
    estatusProductivo: 'Seca',
    lote: 'APR-01',
    edadAnos: 1.2,
    partos: 0,
    ultimoPartoAborto: undefined,
    ultimoServicio: '2026-05-15',
    reproductor: 'CHV-01 Saanen Puro'
  },
  // EQUINOS
  {
    practico: 'EQU-301',
    unico: 'EQU-0301',
    categoria: 'Yegua',
    especie: 'Equinos',
    estatus: 'Activo',
    estatusReproductivo: 'Preñada',
    estatusProductivo: 'Lactancia',
    lote: 'CAB-01',
    edadAnos: 7.2,
    partos: 3,
    ultimoPartoAborto: '2026-07-08',
    ultimoServicio: '2025-10-20',
    reproductor: 'SEM-01 Padrillo Cuarto de Milla'
  },
  {
    practico: 'EQU-302',
    unico: 'EQU-0302',
    categoria: 'Yegua',
    especie: 'Equinos',
    estatus: 'Activo',
    estatusReproductivo: 'Vacía',
    estatusProductivo: 'Trabajo',
    lote: 'CAB-01',
    edadAnos: 5.5,
    partos: 1,
    ultimoPartoAborto: '2025-08-14',
    ultimoServicio: '2026-06-18',
    reproductor: 'SEM-02 Criollo Venezolano'
  },
  {
    practico: 'EQU-303',
    unico: 'EQU-0303',
    categoria: 'Potranca',
    especie: 'Equinos',
    estatus: 'Activo',
    estatusReproductivo: 'En espera',
    estatusProductivo: 'Seca',
    lote: 'CAB-01',
    edadAnos: 2.1,
    partos: 0,
    ultimoPartoAborto: undefined,
    ultimoServicio: '2026-08-10',
    reproductor: 'SEM-01 Padrillo Cuarto de Milla'
  },
  // AVES DE CORRAL
  {
    practico: 'AVE-L01',
    unico: 'AVE-0001',
    categoria: 'Gallina Ponedora',
    especie: 'Aves de corral',
    estatus: 'Activo',
    estatusReproductivo: 'Preñada',
    estatusProductivo: 'Postura',
    lote: 'GALP-01',
    edadAnos: 1.1,
    partos: 1,
    ultimoPartoAborto: '2026-03-01',
    ultimoServicio: '2026-09-02',
    reproductor: 'Lote Hy-Line Brown'
  },
  {
    practico: 'AVE-L02',
    unico: 'AVE-0002',
    categoria: 'Gallina Ponedora',
    especie: 'Aves de corral',
    estatus: 'Activo',
    estatusReproductivo: 'Vacía',
    estatusProductivo: 'Postura',
    lote: 'GALP-02',
    edadAnos: 0.9,
    partos: 1,
    ultimoPartoAborto: '2026-05-10',
    ultimoServicio: undefined,
    reproductor: 'Lote Lohmann White'
  },
  {
    practico: 'AVE-P01',
    unico: 'AVE-0003',
    categoria: 'Pava',
    especie: 'Aves de corral',
    estatus: 'Activo',
    estatusReproductivo: 'Preñada',
    estatusProductivo: 'Postura',
    lote: 'GALP-03',
    edadAnos: 1.4,
    partos: 2,
    ultimoPartoAborto: '2026-02-15',
    ultimoServicio: '2026-08-26',
    reproductor: 'Lote Nicholas White'
  }
];

/* =========================================================================
 * 2. PRÓXIMAS A SECAR (/reports/nexttodry)
 * ========================================================================= */

export const MOCK_PROXIMAS_SECAR: ProximaSecarEntity[] = [
  {
    practico: 'CW010',
    unico: 'CW010',
    categoria: 'Vaca',
    estatus: 'Activo',
    lote: 'ESCT',
    ultimoPartoAborto: '2025-12-05',
    ultimoTipoPartoAborto: 'Normal',
    ultimoServicio: '2026-03-15',
    reproductor: 'BL001 - Sultán del Valle',
    fechaProximoSecado: '2026-10-20',
    fechaProximoParto: '2026-12-20',
    diasProximoSecado: 39,
    diasProximoParto: 100,
    ultimoPesajeLecheKg: 9.4,
    fechaUltimoPesajeLeche: '2026-09-01'
  },
  {
    practico: 'VC-88',
    unico: 'VC-88',
    categoria: 'Vaca',
    estatus: 'Activo',
    lote: '01',
    ultimoPartoAborto: '2025-11-20',
    ultimoTipoPartoAborto: 'Normal',
    ultimoServicio: '2026-02-25',
    reproductor: 'BL001 - Sultán del Valle',
    fechaProximoSecado: '2026-09-30',
    fechaProximoParto: '2026-11-30',
    diasProximoSecado: 19,
    diasProximoParto: 80,
    ultimoPesajeLecheKg: 8.2,
    fechaUltimoPesajeLeche: '2026-09-01'
  },
  {
    practico: 'CW004',
    unico: 'CW004',
    categoria: 'Vaca',
    estatus: 'Activo',
    lote: 'ESCT',
    ultimoPartoAborto: '2026-01-20',
    ultimoTipoPartoAborto: 'Normal',
    ultimoServicio: '2026-04-12',
    reproductor: 'SM01 - Gyr Lechero',
    fechaProximoSecado: '2026-11-15',
    fechaProximoParto: '2027-01-15',
    diasProximoSecado: 65,
    diasProximoParto: 126,
    ultimoPesajeLecheKg: 11.5,
    fechaUltimoPesajeLeche: '2026-08-25'
  }
];

/* =========================================================================
 * 3. PRÓXIMAS A PARIR (/reports/nexttobirth)
 * ========================================================================= */

export const MOCK_PROXIMAS_PARIR: ProximaParirEntity[] = [
  {
    practico: 'CW003',
    unico: 'CW003',
    categoria: 'Vaca',
    estatus: 'Activo',
    lote: 'SEC1',
    ultimoPartoAborto: '2025-08-30',
    partos: 4,
    montas: 0,
    inseminaciones: 1,
    transplantes: 0,
    ultimoServicio: '2025-12-10',
    reproductor: 'BL001 - Sultán del Valle',
    fechaProximoParto: '2026-09-18',
    diasProximoParto: 7,
    ultimoPesoKg: 520,
    fechaUltimoPeso: '2026-08-15',
    fechaSecado: '2026-07-18',
    diasSeca: 55
  },
  {
    practico: 'CW015',
    unico: 'CW015',
    categoria: 'Novilla',
    estatus: 'Activo',
    lote: 'ESCT',
    ultimoPartoAborto: undefined,
    partos: 0,
    montas: 1,
    inseminaciones: 0,
    transplantes: 0,
    ultimoServicio: '2026-02-10',
    reproductor: 'BL001 - Sultán del Valle',
    fechaProximoParto: '2026-11-17',
    diasProximoParto: 67,
    ultimoPesoKg: 440,
    fechaUltimoPeso: '2026-08-20',
    fechaSecado: undefined,
    diasSeca: undefined
  },
  {
    practico: 'VC-88',
    unico: 'VC-88',
    categoria: 'Vaca',
    estatus: 'Activo',
    lote: '01',
    ultimoPartoAborto: '2025-11-20',
    partos: 3,
    montas: 0,
    inseminaciones: 1,
    transplantes: 0,
    ultimoServicio: '2026-02-25',
    reproductor: 'BL001 - Sultán del Valle',
    fechaProximoParto: '2026-11-30',
    diasProximoParto: 80,
    ultimoPesoKg: 495,
    fechaUltimoPeso: '2026-08-10',
    fechaSecado: '2026-09-30',
    diasSeca: 0,
    especie: 'Bovinos',
    duracionGestacionDias: 283
  },
  // PORCINOS (Gestación: 114 días)
  {
    practico: 'POR-101',
    unico: 'POR-0101',
    categoria: 'Cerda Reproductora',
    especie: 'Porcinos',
    estatus: 'Activo',
    lote: 'PIARA-01',
    ultimoPartoAborto: '2026-05-18',
    partos: 3,
    montas: 0,
    inseminaciones: 1,
    transplantes: 0,
    ultimoServicio: '2026-06-01',
    reproductor: 'VER-01 Pietrain Duroc',
    fechaProximoParto: '2026-09-23',
    diasProximoParto: 11,
    ultimoPesoKg: 225,
    fechaUltimoPeso: '2026-09-01',
    fechaSecado: undefined,
    diasSeca: undefined,
    duracionGestacionDias: 114
  },
  // CAPRINOS (Gestación: 150 días)
  {
    practico: 'CAP-201',
    unico: 'CAP-0201',
    categoria: 'Cabra Lechera',
    especie: 'Caprinos',
    estatus: 'Activo',
    lote: 'APR-01',
    ultimoPartoAborto: '2025-12-10',
    partos: 3,
    montas: 1,
    inseminaciones: 0,
    transplantes: 0,
    ultimoServicio: '2026-04-28',
    reproductor: 'CHV-01 Saanen Puro',
    fechaProximoParto: '2026-09-25',
    diasProximoParto: 13,
    ultimoPesoKg: 62,
    fechaUltimoPeso: '2026-09-02',
    fechaSecado: '2026-07-25',
    diasSeca: 49,
    duracionGestacionDias: 150
  },
  {
    practico: 'CAP-203',
    unico: 'CAP-0203',
    categoria: 'Cabritona',
    especie: 'Caprinos',
    estatus: 'Activo',
    lote: 'APR-01',
    ultimoPartoAborto: undefined,
    partos: 0,
    montas: 1,
    inseminaciones: 0,
    transplantes: 0,
    ultimoServicio: '2026-05-15',
    reproductor: 'CHV-01 Saanen Puro',
    fechaProximoParto: '2026-10-12',
    diasProximoParto: 30,
    ultimoPesoKg: 42,
    fechaUltimoPeso: '2026-09-01',
    fechaSecado: undefined,
    diasSeca: undefined,
    duracionGestacionDias: 150
  },
  // BÚFALOS (Gestación: 310 días)
  {
    practico: 'BUF-01',
    unico: 'BUF-0001',
    categoria: 'Búfala',
    especie: 'Búfalos',
    estatus: 'Activo',
    lote: 'BUF-01',
    ultimoPartoAborto: '2025-10-15',
    partos: 3,
    montas: 1,
    inseminaciones: 0,
    transplantes: 0,
    ultimoServicio: '2025-11-20',
    reproductor: 'PAD-BUF01 Murrah',
    fechaProximoParto: '2026-09-26',
    diasProximoParto: 14,
    ultimoPesoKg: 640,
    fechaUltimoPeso: '2026-09-01',
    fechaSecado: '2026-07-26',
    diasSeca: 48,
    duracionGestacionDias: 310
  },
  {
    practico: 'BUF-03',
    unico: 'BUF-0003',
    categoria: 'Bubilla',
    especie: 'Búfalos',
    estatus: 'Activo',
    lote: 'BUF-01',
    ultimoPartoAborto: undefined,
    partos: 0,
    montas: 0,
    inseminaciones: 1,
    transplantes: 0,
    ultimoServicio: '2026-01-10',
    reproductor: 'PAD-BUF01 Murrah',
    fechaProximoParto: '2026-11-16',
    diasProximoParto: 65,
    ultimoPesoKg: 490,
    fechaUltimoPeso: '2026-08-28',
    fechaSecado: undefined,
    diasSeca: undefined,
    duracionGestacionDias: 310
  },
  // EQUINOS (Gestación: 340 días)
  {
    practico: 'EQU-301',
    unico: 'EQU-0301',
    categoria: 'Yegua',
    especie: 'Equinos',
    estatus: 'Activo',
    lote: 'CAB-01',
    ultimoPartoAborto: '2025-08-10',
    partos: 3,
    montas: 0,
    inseminaciones: 1,
    transplantes: 0,
    ultimoServicio: '2025-10-20',
    reproductor: 'SEM-01 Padrillo Cuarto de Milla',
    fechaProximoParto: '2026-09-25',
    diasProximoParto: 13,
    ultimoPesoKg: 480,
    fechaUltimoPeso: '2026-09-05',
    fechaSecado: undefined,
    diasSeca: undefined,
    duracionGestacionDias: 340
  },
  // AVES DE CORRAL (Incubación: 21 días gallinas, 28 días pavos)
  {
    practico: 'AVE-L01',
    unico: 'AVE-0001',
    categoria: 'Gallina Ponedora',
    especie: 'Aves de corral',
    estatus: 'Activo',
    lote: 'GALP-01',
    ultimoPartoAborto: '2026-03-01',
    partos: 1,
    montas: 1,
    inseminaciones: 0,
    transplantes: 0,
    ultimoServicio: '2026-09-02',
    reproductor: 'Lote Hy-Line Brown',
    fechaProximoParto: '2026-09-23',
    diasProximoParto: 11,
    ultimoPesoKg: 1.85,
    fechaUltimoPeso: '2026-09-05',
    fechaSecado: undefined,
    diasSeca: undefined,
    duracionGestacionDias: 21
  },
  {
    practico: 'AVE-P01',
    unico: 'AVE-0003',
    categoria: 'Pava',
    especie: 'Aves de corral',
    estatus: 'Activo',
    lote: 'GALP-03',
    ultimoPartoAborto: '2026-02-15',
    partos: 2,
    montas: 1,
    inseminaciones: 0,
    transplantes: 0,
    ultimoServicio: '2026-08-26',
    reproductor: 'Lote Nicholas White',
    fechaProximoParto: '2026-09-23',
    diasProximoParto: 11,
    ultimoPesoKg: 9.2,
    fechaUltimoPeso: '2026-09-04',
    fechaSecado: undefined,
    diasSeca: undefined,
    duracionGestacionDias: 28
  }
];

/* =========================================================================
 * 4. PRÓXIMAS A REVISAR (/reports/nexttocheck)
 * ========================================================================= */

export const MOCK_PROXIMAS_REVISAR: ProximaRevisarEntity[] = [
  {
    practico: 'CW002',
    unico: 'CW002',
    categoria: 'Vaca',
    estatus: 'Activo',
    lote: 'ESCT',
    ultimoPartoAborto: '2025-11-14',
    partos: 4,
    montas: 0,
    inseminaciones: 1,
    transplantes: 0,
    ultimoServicio: '2026-08-02',
    reproductor: 'SM02 - Brahman Rojo',
    ultimaRevision: '2026-07-15',
    revisiones: 2,
    ultimoDiagnostico: 'Cuerpo lúteo funcional',
    ultimoTratamiento: 'Inseminación a celo detectado',
    proximaRevision: '2026-09-15',
    diasProximaRevision: 4
  },
  {
    practico: 'CW006',
    unico: 'CW006',
    categoria: 'Vaca',
    estatus: 'Activo',
    lote: 'ESCT',
    ultimoPartoAborto: '2026-03-05',
    partos: 3,
    montas: 1,
    inseminaciones: 0,
    transplantes: 0,
    ultimoServicio: '2026-07-28',
    reproductor: 'SM02 - Brahman Rojo',
    ultimaRevision: '2026-07-10',
    revisiones: 1,
    ultimoDiagnostico: 'Revisión postparto favorable',
    ultimoTratamiento: undefined,
    proximaRevision: '2026-09-12',
    diasProximaRevision: 1
  },
  {
    practico: 'CW013',
    unico: 'CW013',
    categoria: 'Novilla',
    estatus: 'Activo',
    lote: 'ESCT',
    ultimoPartoAborto: undefined,
    partos: 0,
    montas: 0,
    inseminaciones: 1,
    transplantes: 0,
    ultimoServicio: '2026-08-15',
    reproductor: 'SM01 - Gyr Lechero',
    ultimaRevision: '2026-08-01',
    revisiones: 1,
    ultimoDiagnostico: 'Tracto reproductivo clase 5',
    ultimoTratamiento: 'Protocolo IATF',
    proximaRevision: '2026-09-25',
    diasProximaRevision: 14
  }
];

/* =========================================================================
 * 5. ANIMALES SECOS (/reports/drycows)
 * ========================================================================= */

export const MOCK_ANIMALES_SECOS: AnimalSecoEntity[] = [
  {
    practico: 'CW003',
    unico: 'CW003',
    categoria: 'Vaca',
    estatus: 'Activo',
    estatusReproductivo: 'Preñada',
    estatusProductivo: 'Seca',
    lote: 'SEC1',
    ultimoParto: '2025-08-30',
    ultimoServicio: '2025-12-10',
    diasServidaActual: 275,
    fechaProximoParto: '2026-09-18',
    diasSeca: 55,
    diasEnProduccion: 290
  },
  {
    practico: 'CW007',
    unico: 'CW007',
    categoria: 'Vaca',
    estatus: 'Activo',
    estatusReproductivo: 'Vacía',
    estatusProductivo: 'Seca',
    lote: 'SEC1',
    ultimoParto: '2025-06-12',
    ultimoServicio: '2026-05-14',
    diasServidaActual: 120,
    fechaProximoParto: undefined,
    diasSeca: 92,
    diasEnProduccion: 270
  },
  {
    practico: 'CW012',
    unico: 'CW012',
    categoria: 'Vaca',
    estatus: 'Activo',
    estatusReproductivo: 'Vacía',
    estatusProductivo: 'Seca',
    lote: 'SEC1',
    ultimoParto: '2025-05-18',
    ultimoServicio: '2026-04-20',
    diasServidaActual: 144,
    fechaProximoParto: undefined,
    diasSeca: 115,
    diasEnProduccion: 265
  },
  {
    practico: 'CW001BBB',
    unico: 'CW001BBB',
    categoria: 'Vaca',
    estatus: 'Activo',
    estatusReproductivo: 'Vacía',
    estatusProductivo: 'Seca',
    lote: 'SEC1',
    ultimoParto: '2025-07-22',
    ultimoServicio: '2026-05-30',
    diasServidaActual: 104,
    fechaProximoParto: undefined,
    diasSeca: 75,
    diasEnProduccion: 280
  }
];

/* =========================================================================
 * 6. ANIMALES LACTANDO (/reports/cowsinproduction)
 * ========================================================================= */

export const MOCK_ANIMALES_LACTANDO: AnimalLactandoEntity[] = [
  {
    practico: '0002',
    unico: '0002',
    categoria: 'Vaca',
    estatus: 'Activo',
    situacionReproductivaActual: 'Vacía',
    situacionProductivaActual: 'Ordeño',
    lote: '01',
    ultimoParto: '2026-03-22',
    numeroParto: 5,
    ultimoServicio: '2026-06-18',
    reproductor: 'SM01 - Gyr Lechero',
    diasEnProduccion: 173,
    diasParida: 173,
    diasServida: 85,
    proximoParto: undefined,
    fechaProximoSecado: '2026-12-15'
  },
  {
    practico: 'CW002',
    unico: 'CW002',
    categoria: 'Vaca',
    estatus: 'Activo',
    situacionReproductivaActual: 'En espera',
    situacionProductivaActual: 'Ordeño',
    lote: 'ESCT',
    ultimoParto: '2025-11-14',
    numeroParto: 4,
    ultimoServicio: '2026-08-02',
    reproductor: 'SM02 - Brahman Rojo',
    diasEnProduccion: 301,
    diasParida: 301,
    diasServida: 40,
    proximoParto: undefined,
    fechaProximoSecado: '2026-10-30'
  },
  {
    practico: 'CW008',
    unico: 'CW008',
    categoria: 'Vaca',
    estatus: 'Activo',
    situacionReproductivaActual: 'Vacía',
    situacionProductivaActual: 'Ordeño',
    lote: 'ESCT',
    ultimoParto: '2025-10-08',
    numeroParto: 4,
    ultimoServicio: '2026-07-02',
    reproductor: 'SM01 - Gyr Lechero',
    diasEnProduccion: 338,
    diasParida: 338,
    diasServida: 71,
    proximoParto: undefined,
    fechaProximoSecado: '2026-11-01'
  },
  {
    practico: 'CW009',
    unico: 'CW009',
    categoria: 'Vaca',
    estatus: 'Activo',
    situacionReproductivaActual: 'Vacía',
    situacionProductivaActual: 'Ordeño',
    lote: 'ESCT',
    ultimoParto: '2026-01-15',
    numeroParto: 3,
    ultimoServicio: '2026-06-10',
    reproductor: 'BL002 - Rey Criollo',
    diasEnProduccion: 239,
    diasParida: 239,
    diasServida: 93,
    proximoParto: undefined,
    fechaProximoSecado: '2026-12-01'
  },
  {
    practico: 'CW010',
    unico: 'CW010',
    categoria: 'Vaca',
    estatus: 'Activo',
    situacionReproductivaActual: 'Preñada',
    situacionProductivaActual: 'Ordeño',
    lote: 'ESCT',
    ultimoParto: '2025-12-05',
    numeroParto: 2,
    ultimoServicio: '2026-03-15',
    reproductor: 'BL001 - Sultán del Valle',
    diasEnProduccion: 280,
    diasParida: 280,
    diasServida: 180,
    proximoParto: '2026-12-20',
    fechaProximoSecado: '2026-10-20'
  },
  {
    practico: 'VC-88',
    unico: 'VC-88',
    categoria: 'Vaca',
    estatus: 'Activo',
    situacionReproductivaActual: 'Preñada',
    situacionProductivaActual: 'Ordeño',
    lote: '01',
    ultimoParto: '2025-11-20',
    numeroParto: 3,
    ultimoServicio: '2026-02-25',
    reproductor: 'BL001 - Sultán del Valle',
    diasEnProduccion: 295,
    diasParida: 295,
    diasServida: 198,
    proximoParto: '2026-11-30',
    fechaProximoSecado: '2026-09-30'
  },
  {
    practico: 'VC-92',
    unico: 'VC-92',
    categoria: 'Vaca',
    estatus: 'Activo',
    situacionReproductivaActual: 'Vacía',
    situacionProductivaActual: 'Ordeño',
    lote: '01',
    ultimoParto: '2026-02-01',
    numeroParto: 2,
    ultimoServicio: '2026-05-18',
    reproductor: 'BL002 - Rey Criollo',
    diasEnProduccion: 222,
    diasParida: 222,
    diasServida: 116,
    proximoParto: undefined,
    fechaProximoSecado: '2026-12-10',
    especie: 'Bovinos'
  },
  // BÚFALOS (Lactancia Bufalina)
  {
    practico: 'BUF-01',
    unico: 'BUF-0001',
    categoria: 'Búfala',
    especie: 'Búfalos',
    estatus: 'Activo',
    situacionReproductivaActual: 'Preñada',
    situacionProductivaActual: 'Ordeño',
    lote: 'BUF-01',
    ultimoParto: '2025-10-15',
    numeroParto: 3,
    ultimoServicio: '2025-11-20',
    reproductor: 'PAD-BUF01 Murrah',
    diasParida: 332,
    diasServida: 296,
    proximoParto: '2026-09-26',
    fechaProximoSecado: '2026-07-26',
    diasEnProduccion: 332
  },
  {
    practico: 'BUF-02',
    unico: 'BUF-0002',
    categoria: 'Búfala',
    especie: 'Búfalos',
    estatus: 'Activo',
    situacionReproductivaActual: 'Vacía',
    situacionProductivaActual: 'Ordeño',
    lote: 'BUF-01',
    ultimoParto: '2026-02-12',
    numeroParto: 2,
    ultimoServicio: '2026-06-10',
    reproductor: 'PAD-BUF02 Mediterráneo',
    diasParida: 212,
    diasServida: 94,
    proximoParto: undefined,
    fechaProximoSecado: '2026-11-15',
    diasEnProduccion: 212
  },
  // CAPRINOS (Ordeño Caprino en Tarima)
  {
    practico: 'CAP-201',
    unico: 'CAP-0201',
    categoria: 'Cabra Lechera',
    especie: 'Caprinos',
    estatus: 'Activo',
    situacionReproductivaActual: 'Preñada',
    situacionProductivaActual: 'Ordeño',
    lote: 'APR-01',
    ultimoParto: '2025-12-10',
    numeroParto: 3,
    ultimoServicio: '2026-04-28',
    reproductor: 'CHV-01 Saanen Puro',
    diasParida: 276,
    diasServida: 137,
    proximoParto: '2026-09-25',
    fechaProximoSecado: '2026-07-25',
    diasEnProduccion: 276
  },
  {
    practico: 'CAP-202',
    unico: 'CAP-0202',
    categoria: 'Cabra Lechera',
    especie: 'Caprinos',
    estatus: 'Activo',
    situacionReproductivaActual: 'Vacía',
    situacionProductivaActual: 'Ordeño',
    lote: 'APR-01',
    ultimoParto: '2026-03-14',
    numeroParto: 2,
    ultimoServicio: '2026-07-05',
    reproductor: 'CHV-02 Alpino Francés',
    diasParida: 182,
    diasServida: 69,
    proximoParto: undefined,
    fechaProximoSecado: '2026-10-15',
    diasEnProduccion: 182
  },
  // PORCINOS (Cerdas en Lactancia de Camada)
  {
    practico: 'POR-102',
    unico: 'POR-0102',
    categoria: 'Cerda Reproductora',
    especie: 'Porcinos',
    estatus: 'Activo',
    situacionReproductivaActual: 'Vacía',
    situacionProductivaActual: 'Lactancia',
    lote: 'PIARA-01',
    ultimoParto: '2026-08-25',
    numeroParto: 2,
    ultimoServicio: undefined,
    reproductor: 'VER-02 Landrace',
    diasParida: 18,
    diasServida: undefined,
    proximoParto: undefined,
    fechaProximoSecado: '2026-09-22',
    diasEnProduccion: 18
  },
  // EQUINOS (Yeguas con Cría al Pie)
  {
    practico: 'EQU-301',
    unico: 'EQU-0301',
    categoria: 'Yegua',
    especie: 'Equinos',
    estatus: 'Activo',
    situacionReproductivaActual: 'Preñada',
    situacionProductivaActual: 'Lactancia',
    lote: 'CAB-01',
    ultimoParto: '2026-07-08',
    numeroParto: 3,
    ultimoServicio: '2025-10-20',
    reproductor: 'SEM-01 Padrillo Cuarto de Milla',
    diasParida: 66,
    diasServida: 327,
    proximoParto: '2026-09-25',
    fechaProximoSecado: '2026-12-08',
    diasEnProduccion: 66
  },
  // AVES DE CORRAL (Lotes en Postura Activa)
  {
    practico: 'AVE-L01',
    unico: 'AVE-0001',
    categoria: 'Gallina Ponedora',
    especie: 'Aves de corral',
    estatus: 'Activo',
    situacionReproductivaActual: 'Vacía',
    situacionProductivaActual: 'Postura',
    lote: 'GALP-01',
    ultimoParto: '2026-03-01',
    numeroParto: 1,
    ultimoServicio: undefined,
    reproductor: 'Lote Hy-Line Brown',
    diasParida: 195,
    diasServida: undefined,
    proximoParto: undefined,
    fechaProximoSecado: '2027-02-01',
    diasEnProduccion: 195
  },
  {
    practico: 'AVE-L02',
    unico: 'AVE-0002',
    categoria: 'Gallina Ponedora',
    especie: 'Aves de corral',
    estatus: 'Activo',
    situacionReproductivaActual: 'Vacía',
    situacionProductivaActual: 'Postura',
    lote: 'GALP-02',
    ultimoParto: '2026-05-10',
    numeroParto: 1,
    ultimoServicio: undefined,
    reproductor: 'Lote Lohmann White',
    diasParida: 125,
    diasServida: undefined,
    proximoParto: undefined,
    fechaProximoSecado: '2027-04-10',
    diasEnProduccion: 125
  }
];

/* =========================================================================
 * 7. ANIMALES CRIANDO (/reports/cowsraising)
 * ========================================================================= */

export const MOCK_ANIMALES_CRIANDO: AnimalCriandoEntity[] = [
  {
    practico: '0001',
    unico: '0001',
    categoria: 'Vaca',
    estatus: 'Activo',
    lote: '01',
    ultimoParto: '2026-05-10',
    codigosCriasUltimoParto: 'BC-101',
    diasParidaActual: 124
  },
  {
    practico: 'CW004',
    unico: 'CW004',
    categoria: 'Vaca',
    estatus: 'Activo',
    lote: 'ESCT',
    ultimoParto: '2026-01-20',
    codigosCriasUltimoParto: 'BR-01',
    diasParidaActual: 234
  },
  {
    practico: 'CW005',
    unico: 'CW005',
    categoria: 'Vaca',
    estatus: 'Activo',
    lote: 'ESCT',
    ultimoParto: '2026-02-18',
    codigosCriasUltimoParto: 'BC-102',
    diasParidaActual: 205
  },
  {
    practico: 'CW006',
    unico: 'CW006',
    categoria: 'Vaca',
    estatus: 'Activo',
    lote: 'ESCT',
    ultimoParto: '2026-03-05',
    codigosCriasUltimoParto: 'BC-103',
    diasParidaActual: 190
  },
  {
    practico: 'CW011',
    unico: 'CW011',
    categoria: 'Vaca',
    estatus: 'Activo',
    lote: 'ESCT',
    ultimoParto: '2026-04-10',
    codigosCriasUltimoParto: 'BR-02',
    diasParidaActual: 154
  },
  {
    practico: 'CW014',
    unico: 'CW014',
    categoria: 'Vaca',
    estatus: 'Activo',
    lote: 'ESCT',
    ultimoParto: '2026-04-28',
    codigosCriasUltimoParto: 'BC-104',
    diasParidaActual: 136
  }
];

/* =========================================================================
 * 8. NO VIENTRES (/reports/nodams)
 * Machos de cualquier edad y hembras antes del servicio (becerras/mautas)
 * ========================================================================= */

export const MOCK_NO_VIENTRES: NoVientreEntity[] = [
  {
    practico: 'BC-101',
    unico: 'VE-2026-101',
    categoria: 'Becerro',
    estatus: 'Activo',
    lote: '01',
    fechaNacimiento: '2026-05-10',
    edadMeses: 4.0,
    composicion: 'Carora 75% / Brahman 25%',
    penultimoPesoKg: 78,
    fechaPenultimoPeso: '2026-07-10',
    ultimoPesoKg: 118,
    fechaUltimoPeso: '2026-09-05',
    gananciaParcialGramosDia: 701,
    gananciaGlobalGramosDia: 685,
    pesoIngresoKg: 36,
    fechaPesoIngreso: '2026-05-10'
  },
  {
    practico: 'BC-104',
    unico: 'VE-2026-104',
    categoria: 'Becerro',
    estatus: 'Activo',
    lote: 'POT1',
    fechaNacimiento: '2026-08-14',
    edadMeses: 0.9,
    composicion: 'Carora Puro',
    penultimoPesoKg: 35,
    fechaPenultimoPeso: '2026-08-14',
    ultimoPesoKg: 52,
    fechaUltimoPeso: '2026-09-08',
    gananciaParcialGramosDia: 680,
    gananciaGlobalGramosDia: 680,
    pesoIngresoKg: 35,
    fechaPesoIngreso: '2026-08-14'
  },
  {
    practico: 'BR-01',
    unico: 'VE-2026-BR01',
    categoria: 'Becerra',
    estatus: 'Activo',
    lote: 'POT1',
    fechaNacimiento: '2026-01-20',
    edadMeses: 7.7,
    composicion: 'Gyr Lechero 50% / Holstein 50%',
    penultimoPesoKg: 145,
    fechaPenultimoPeso: '2026-06-20',
    ultimoPesoKg: 198,
    fechaUltimoPeso: '2026-08-30',
    gananciaParcialGramosDia: 746,
    gananciaGlobalGramosDia: 710,
    pesoIngresoKg: 32,
    fechaPesoIngreso: '2026-01-20'
  },
  {
    practico: 'MT-01',
    unico: 'VE-2025-MT01',
    categoria: 'Maute',
    estatus: 'Activo',
    lote: 'ESCT',
    fechaNacimiento: '2025-06-15',
    edadMeses: 14.8,
    composicion: 'Brahman Blanco',
    penultimoPesoKg: 285,
    fechaPenultimoPeso: '2026-05-15',
    ultimoPesoKg: 345,
    fechaUltimoPeso: '2026-08-20',
    gananciaParcialGramosDia: 618,
    gananciaGlobalGramosDia: 690,
    pesoIngresoKg: 38,
    fechaPesoIngreso: '2025-06-15'
  },
  {
    practico: 'MA-05',
    unico: 'VE-2025-MA05',
    categoria: 'Mauta',
    estatus: 'Activo',
    lote: 'ESCT',
    fechaNacimiento: '2025-05-10',
    edadMeses: 16.0,
    composicion: 'Carora 100%',
    penultimoPesoKg: 260,
    fechaPenultimoPeso: '2026-04-10',
    ultimoPesoKg: 322,
    fechaUltimoPeso: '2026-08-15',
    gananciaParcialGramosDia: 488,
    gananciaGlobalGramosDia: 595,
    pesoIngresoKg: 34,
    fechaPesoIngreso: '2025-05-10'
  },
  {
    practico: 'NV-02',
    unico: 'VE-2024-NV02',
    categoria: 'Novillo',
    estatus: 'Activo',
    lote: 'ESCT',
    fechaNacimiento: '2024-09-12',
    edadMeses: 24.0,
    composicion: 'Guzerá F1',
    penultimoPesoKg: 410,
    fechaPenultimoPeso: '2026-05-12',
    ultimoPesoKg: 468,
    fechaUltimoPeso: '2026-08-25',
    gananciaParcialGramosDia: 552,
    gananciaGlobalGramosDia: 590,
    pesoIngresoKg: 37,
    fechaPesoIngreso: '2024-09-12',
    especie: 'Bovinos'
  },
  // BÚFALOS
  {
    practico: 'BUC-01',
    unico: 'BUF-2026-01',
    categoria: 'Bucerro',
    especie: 'Búfalos',
    estatus: 'Activo',
    lote: 'BUF-01',
    fechaNacimiento: '2026-04-10',
    edadMeses: 5.1,
    composicion: 'Murrah 100%',
    penultimoPesoKg: 95,
    fechaPenultimoPeso: '2026-07-10',
    ultimoPesoKg: 142,
    fechaUltimoPeso: '2026-09-05',
    gananciaParcialGramosDia: 825,
    gananciaGlobalGramosDia: 730,
    pesoIngresoKg: 38,
    fechaPesoIngreso: '2026-04-10'
  },
  {
    practico: 'BUF-CEB',
    unico: 'BUF-2024-C01',
    categoria: 'Búfalo de Ceba',
    especie: 'Búfalos',
    estatus: 'Activo',
    lote: 'BUF-01',
    fechaNacimiento: '2024-11-15',
    edadMeses: 22.0,
    composicion: 'Mediterráneo',
    penultimoPesoKg: 380,
    fechaPenultimoPeso: '2026-06-15',
    ultimoPesoKg: 445,
    fechaUltimoPeso: '2026-08-30',
    gananciaParcialGramosDia: 855,
    gananciaGlobalGramosDia: 615,
    pesoIngresoKg: 40,
    fechaPesoIngreso: '2024-11-15'
  },
  // PORCINOS
  {
    practico: 'POR-L01',
    unico: 'POR-2026-L01',
    categoria: 'Lechón',
    especie: 'Porcinos',
    estatus: 'Activo',
    lote: 'PIARA-01',
    fechaNacimiento: '2026-08-01',
    edadMeses: 1.4,
    composicion: 'Landrace x Duroc',
    penultimoPesoKg: 7.5,
    fechaPenultimoPeso: '2026-08-20',
    ultimoPesoKg: 14.8,
    fechaUltimoPeso: '2026-09-08',
    gananciaParcialGramosDia: 384,
    gananciaGlobalGramosDia: 320,
    pesoIngresoKg: 1.4,
    fechaPesoIngreso: '2026-08-01'
  },
  {
    practico: 'POR-CEB01',
    unico: 'POR-2026-C01',
    categoria: 'Cerdo de Ceba',
    especie: 'Porcinos',
    estatus: 'Activo',
    lote: 'PIARA-01',
    fechaNacimiento: '2026-04-15',
    edadMeses: 4.9,
    composicion: 'Pietrain Comercial',
    penultimoPesoKg: 68,
    fechaPenultimoPeso: '2026-08-01',
    ultimoPesoKg: 94,
    fechaUltimoPeso: '2026-09-05',
    gananciaParcialGramosDia: 742,
    gananciaGlobalGramosDia: 630,
    pesoIngresoKg: 1.5,
    fechaPesoIngreso: '2026-04-15'
  },
  {
    practico: 'VER-02',
    unico: 'POR-2025-V02',
    categoria: 'Verraco',
    especie: 'Porcinos',
    estatus: 'Activo',
    lote: 'PIARA-01',
    fechaNacimiento: '2025-08-10',
    edadMeses: 13.1,
    composicion: 'Landrace Puro',
    penultimoPesoKg: 180,
    fechaPenultimoPeso: '2026-06-10',
    ultimoPesoKg: 215,
    fechaUltimoPeso: '2026-08-25',
    gananciaParcialGramosDia: 460,
    gananciaGlobalGramosDia: 540,
    pesoIngresoKg: 1.6,
    fechaPesoIngreso: '2025-08-10'
  },
  // CAPRINOS
  {
    practico: 'CAP-CR01',
    unico: 'CAP-2026-01',
    categoria: 'Cabrito',
    especie: 'Caprinos',
    estatus: 'Activo',
    lote: 'APR-01',
    fechaNacimiento: '2026-06-20',
    edadMeses: 2.7,
    composicion: 'Saanen 75% / Criollo 25%',
    penultimoPesoKg: 10.5,
    fechaPenultimoPeso: '2026-08-10',
    ultimoPesoKg: 16.2,
    fechaUltimoPeso: '2026-09-08',
    gananciaParcialGramosDia: 196,
    gananciaGlobalGramosDia: 175,
    pesoIngresoKg: 3.2,
    fechaPesoIngreso: '2026-06-20'
  },
  {
    practico: 'CHV-02',
    unico: 'CAP-2025-CH02',
    categoria: 'Chivo Reproductor',
    especie: 'Caprinos',
    estatus: 'Activo',
    lote: 'APR-01',
    fechaNacimiento: '2025-05-14',
    edadMeses: 15.9,
    composicion: 'Alpino Francés',
    penultimoPesoKg: 52,
    fechaPenultimoPeso: '2026-05-14',
    ultimoPesoKg: 64,
    fechaUltimoPeso: '2026-08-20',
    gananciaParcialGramosDia: 122,
    gananciaGlobalGramosDia: 125,
    pesoIngresoKg: 3.5,
    fechaPesoIngreso: '2025-05-14'
  },
  // EQUINOS
  {
    practico: 'EQU-PT01',
    unico: 'EQU-2025-PT01',
    categoria: 'Potro',
    especie: 'Equinos',
    estatus: 'Activo',
    lote: 'CAB-01',
    fechaNacimiento: '2025-10-12',
    edadMeses: 11.0,
    composicion: 'Cuarto de Milla',
    penultimoPesoKg: 230,
    fechaPenultimoPeso: '2026-06-12',
    ultimoPesoKg: 295,
    fechaUltimoPeso: '2026-09-02',
    gananciaParcialGramosDia: 792,
    gananciaGlobalGramosDia: 740,
    pesoIngresoKg: 45,
    fechaPesoIngreso: '2025-10-12'
  },
  {
    practico: 'EQU-CAB01',
    unico: 'EQU-2022-CB01',
    categoria: 'Caballo',
    especie: 'Equinos',
    estatus: 'Activo',
    lote: 'CAB-01',
    fechaNacimiento: '2022-04-15',
    edadMeses: 52.9,
    composicion: 'Criollo Llanero',
    penultimoPesoKg: 420,
    fechaPenultimoPeso: '2026-05-15',
    ultimoPesoKg: 435,
    fechaUltimoPeso: '2026-08-20',
    gananciaParcialGramosDia: 154,
    gananciaGlobalGramosDia: 250,
    pesoIngresoKg: 40,
    fechaPesoIngreso: '2022-04-15'
  },
  // AVES DE CORRAL
  {
    practico: 'AVE-ENG01',
    unico: 'AVE-2026-E01',
    categoria: 'Pollos de Engorde',
    especie: 'Aves de corral',
    estatus: 'Activo',
    lote: 'GALP-04',
    fechaNacimiento: '2026-08-05',
    edadMeses: 1.2,
    composicion: 'Cobb 500 Broiler',
    penultimoPesoKg: 1.4,
    fechaPenultimoPeso: '2026-08-25',
    ultimoPesoKg: 2.65,
    fechaUltimoPeso: '2026-09-08',
    gananciaParcialGramosDia: 89,
    gananciaGlobalGramosDia: 72,
    pesoIngresoKg: 0.045,
    fechaPesoIngreso: '2026-08-05'
  },
  {
    practico: 'AVE-GL01',
    unico: 'AVE-2025-G01',
    categoria: 'Gallos Finos',
    especie: 'Aves de corral',
    estatus: 'Activo',
    lote: 'GALP-05',
    fechaNacimiento: '2025-06-10',
    edadMeses: 15.1,
    composicion: 'Gallos de Combate Marañón',
    penultimoPesoKg: 2.1,
    fechaPenultimoPeso: '2026-06-10',
    ultimoPesoKg: 2.3,
    fechaUltimoPeso: '2026-08-20',
    gananciaParcialGramosDia: 2.8,
    gananciaGlobalGramosDia: 4.8,
    pesoIngresoKg: 0.040,
    fechaPesoIngreso: '2025-06-10'
  }
];
